/*
Feature Name: CARD_CT_VAR_BRANCH_REG_3M
Derived From: DW_CARD_MASTER_DIM, CINS_TMP_CUSTOMER_{RPT_DT_TBL}
*/
INSERT INTO {TBL_NM}
SELECT CUSTOMER_CDE,
       'CARD_CT_VAR_BRANCH_REG_3M' FTR_NM,
                                   count(DISTINCT sub_branch_cde)FTR_VAL,
                                   TO_DATE('{RPT_DT}', 'DD-MM-YY') AS RPT_DT,
                                   CURRENT_TIMESTAMP ADD_TSTP
FROM DW_ANALYTICS.DW_CARD_MASTER_DIM
WHERE anniv_dt < TO_DATE('{RPT_DT}', 'DD-MM-YY')
  AND anniv_dt >= ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -3)
  AND CUSTOMER_CDE IN
    (SELECT CUSTOMER_CDE
     FROM CINS_TMP_CUSTOMER_{RPT_DT_TBL})
GROUP BY CUSTOMER_CDE