/*
Feature Name: DEBT_GRP
Derived From: DW_CUSTOMER_FULL_DIM, DW_CUSTOMER_DIM
*/
INSERT INTO {TBL_NM}
SELECT CUSTOMER_CDE,
       'DEBT_GRP' FTR_NM,
                  DB_GRP_CIC FTR_VAL,
                  TO_DATE('{RPT_DT}', 'DD-MM-YY') AS RPT_DT,
                  CURRENT_TIMESTAMP ADD_TSTP
FROM DW_ANALYTICS.DW_CUSTOMER_FULL_DIM
WHERE DB_GRP_CIC IS NOT NULL
  AND CUSTOMER_CDE IN
    (SELECT CUSTOMER_CDE
     FROM DW_ANALYTICS.DW_CUSTOMER_DIM
     WHERE ACTIVE = 1
       AND COMPANY_KEY = 1
       AND SUB_SECTOR_CDE IN ('1700',
                              '1602')
       AND CUS_OPEN_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY'))