/*
Feature Name: EB_MBIB_HOLD
Derived From: DW_EB_USER, CINS_TMP_CUSTOMER_{RPT_DT_TBL}
*/
INSERT INTO {TBL_NM}
SELECT DISTINCT CUSTOMER_CDE,
                'EB_MBIB_HOLD' FTR_NM,
                1 FTR_VAL,
                TO_DATE('{RPT_DT}', 'DD-MM-YY') AS RPT_DT,
                CURRENT_TIMESTAMP ADD_TSTP
FROM DW_ANALYTICS.DW_EB_USER
WHERE PROCESS_DT IN
    (SELECT MAX(PROCESS_DT)
     FROM DW_ANALYTICS.DW_EB_USER
     WHERE PROCESS_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY') )
  AND DEL_FLG = 'N'
  AND CUSTOMER_CDE IN
    (SELECT CUSTOMER_CDE
     FROM CINS_TMP_CUSTOMER_{RPT_DT_TBL})