/*
Feature Name: EB_MBIB_INACTIVE
Derived From: DW_EB_TRANSACTION_FCT, DW_CUSTOMER_DIM
*/
INSERT INTO {TBL_NM}
SELECT CUSTOMER_CDE,
       'EB_MBIB_INACTIVE' FTR_NM,
                          1 FTR_VAL,
                          TO_DATE('{RPT_DT}', 'DD-MM-YY') AS RPT_DT,
                          CURRENT_TIMESTAMP ADD_TSTP
FROM DW_ANALYTICS.DW_CUSTOMER_DIM
WHERE ACTIVE = 1
  AND COMPANY_KEY = 1
  AND SUB_SECTOR_CDE IN ('1700',
                         '1602')
  AND CUSTOMER_CDE IN
    (SELECT CUSTOMER_CDE
     FROM DW_ANALYTICS.DW_EB_TRANSACTION_FCT
     WHERE TXN_STATUS = 'SUC'
       AND TXN_DT < ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -12)
       AND TXN_DT >= ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -36)
       AND CUSTOMER_CDE IS NOT NULL)
  AND CUSTOMER_CDE NOT IN
    (SELECT CUSTOMER_CDE
     FROM DW_ANALYTICS.DW_EB_TRANSACTION_FCT
     WHERE TXN_STATUS = 'SUC'
       AND TXN_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')
       AND TXN_DT >= ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -12)
       AND CUSTOMER_CDE IS NOT NULL)