/*
Feature Name: EB_MBIB_DAY_SINCE_LTST_TXN
Derived From: DW_EB_TRANSACTION_FCT
*/
INSERT INTO {TBL_NM}
SELECT CUSTOMER_CDE,
       'EB_MBIB_DAY_SINCE_LTST_TXN' FTR_NM,
                                    TO_DATE('{RPT_DT}', 'DD-MM-YY') - NVL(MAX(TXN_DT), ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -36)) FTR_VAL,
                                    TO_CHAR(TO_DATE('{RPT_DT}', 'DD-MM-YY'), 'DD-MM-YYYY') AS RPT_DT,
                                    CURRENT_TIMESTAMP ADD_TSTP
FROM DW_ANALYTICS.DW_EB_TRANSACTION_FCT
WHERE TXN_DT >= ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -36)
  AND TXN_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')
  AND TXN_STATUS = 'SUC'
  AND CUSTOMER_CDE IN
    (SELECT CUSTOMER_CDE
     FROM CINS_TMP_CUST_TEST)
GROUP BY CUSTOMER_CDE;

/*
Feature Name: EB_MBIB_SUM_TXN_AMT_1M, EB_MBIB_SUM_TXN_AMT_3M, EB_MBIB_SUM_TXN_AMT_6M
Derived From: DW_EB_TRANSACTION_FCT
*/
INSERT INTO {TBL_NM}
SELECT CUSTOMER_CDE,
       'EB_MBIB_SUM_TXN_AMT_1M' FTR_NM,
                                NVL(SUM(ABS(AMT_ENTRY_LCL)), 0) FTR_VAL,
                                TO_CHAR(TO_DATE('{RPT_DT}', 'DD-MM-YY'), 'DD-MM-YYYY') AS RPT_DT,
                                CURRENT_TIMESTAMP ADD_TSTP
FROM
  (SELECT DISTINCT TXN_ID,
                   CUSTOMER_CDE,
                   TXN_DT,
                   AMT_ENTRY_LCL
   FROM DW_ANALYTICS.DW_EB_TRANSACTION_FCT
   WHERE TXN_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')
     AND TXN_DT >= ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -1)
     AND TXN_STATUS = 'SUC'
     AND CUSTOMER_CDE IN
       (SELECT CUSTOMER_CDE
        FROM CINS_TMP_CUST_TEST) ) TXN
GROUP BY CUSTOMER_CDE
UNION ALL
SELECT CUSTOMER_CDE,
       'EB_MBIB_SUM_TXN_AMT_3M' FTR_NM,
                                NVL(SUM(ABS(AMT_ENTRY_LCL)), 0) FTR_VAL,
                                TO_CHAR(TO_DATE('{RPT_DT}', 'DD-MM-YY'), 'DD-MM-YYYY') AS RPT_DT,
                                CURRENT_TIMESTAMP ADD_TSTP
FROM
  (SELECT DISTINCT TXN_ID,
                   CUSTOMER_CDE,
                   TXN_DT,
                   AMT_ENTRY_LCL
   FROM DW_ANALYTICS.DW_EB_TRANSACTION_FCT
   WHERE TXN_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')
     AND TXN_DT >= ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -3)
     AND TXN_STATUS = 'SUC'
     AND CUSTOMER_CDE IN
       (SELECT CUSTOMER_CDE
        FROM CINS_TMP_CUST_TEST) ) TXN
GROUP BY CUSTOMER_CDE
UNION ALL
SELECT CUSTOMER_CDE,
       'EB_MBIB_SUM_TXN_AMT_6M' FTR_NM,
                                NVL(SUM(ABS(AMT_ENTRY_LCL)), 0) FTR_VAL,
                                TO_CHAR(TO_DATE('{RPT_DT}', 'DD-MM-YY'), 'DD-MM-YYYY') AS RPT_DT,
                                CURRENT_TIMESTAMP ADD_TSTP
FROM
  (SELECT DISTINCT TXN_ID,
                   CUSTOMER_CDE,
                   TXN_DT,
                   AMT_ENTRY_LCL
   FROM DW_ANALYTICS.DW_EB_TRANSACTION_FCT
   WHERE TXN_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')
     AND TXN_DT >= ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -6)
     AND TXN_STATUS = 'SUC'
     AND CUSTOMER_CDE IN
       (SELECT CUSTOMER_CDE
        FROM CINS_TMP_CUST_TEST) )TXN
GROUP BY CUSTOMER_CDE;

/*
Feature Name: EB_MBIB_CT_TXN_1M, EB_MBIB_CT_TXN_3M, EB_MBIB_CT_TXN_6M
Derived From: DW_EB_TRANSACTION_FCT
*/
INSERT INTO {TBL_NM}
SELECT CUSTOMER_CDE,
       'EB_MBIB_CT_TXN_1M' FTR_NM,
                           COUNT(TXN_ID) FTR_VAL,
                           TO_CHAR(TO_DATE('{RPT_DT}', 'DD-MM-YY'), 'DD-MM-YYYY') AS RPT_DT,
                           CURRENT_TIMESTAMP ADD_TSTP
FROM DW_ANALYTICS.DW_EB_TRANSACTION_FCT
WHERE TXN_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')
  AND TXN_DT >= ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -1)
  AND TXN_STATUS = 'SUC'
  AND CUSTOMER_CDE IN
    (SELECT CUSTOMER_CDE
     FROM CINS_TMP_CUST_TEST)
GROUP BY CUSTOMER_CDE
UNION ALL
SELECT CUSTOMER_CDE,
       'EB_MBIB_CT_TXN_3M' FTR_NM,
                           COUNT(TXN_ID) FTR_VAL,
                           TO_CHAR(TO_DATE('{RPT_DT}', 'DD-MM-YY'), 'DD-MM-YYYY') AS RPT_DT,
                           CURRENT_TIMESTAMP ADD_TSTP
FROM DW_ANALYTICS.DW_EB_TRANSACTION_FCT
WHERE TXN_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')
  AND TXN_DT >= ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -3)
  AND TXN_STATUS = 'SUC'
  AND CUSTOMER_CDE IN
    (SELECT CUSTOMER_CDE
     FROM CINS_TMP_CUST_TEST)
GROUP BY CUSTOMER_CDE
UNION ALL
SELECT CUSTOMER_CDE,
       'EB_MBIB_CT_TXN_6M' FTR_NM,
                           COUNT(TXN_ID) FTR_VAL,
                           TO_CHAR(TO_DATE('{RPT_DT}', 'DD-MM-YY'), 'DD-MM-YYYY') AS RPT_DT,
                           CURRENT_TIMESTAMP ADD_TSTP
FROM DW_ANALYTICS.DW_EB_TRANSACTION_FCT
WHERE TXN_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')
  AND TXN_DT >= ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -6)
  AND TXN_STATUS = 'SUC'
  AND CUSTOMER_CDE IN
    (SELECT CUSTOMER_CDE
     FROM CINS_TMP_CUST_TEST)
GROUP BY CUSTOMER_CDE;

/*
Feature Name: EB_MBIB_INACTIVE
Derived From: DW_EB_TRANSACTION_FCT
*/
INSERT INTO {TBL_NM}
SELECT CUSTOMER_CDE,
       'EB_MBIB_INACTIVE' FTR_NM,
                          1 FTR_VAL,
                          TO_CHAR(TO_DATE('{RPT_DT}', 'DD-MM-YY'), 'DD-MM-YYYY') AS RPT_DT,
                          CURRENT_TIMESTAMP ADD_TSTP
FROM DW_ANALYTICS.DW_CUSTOMER_DIM
WHERE ACTIVE = 1
  AND COMPANY_KEY = 1
  AND SUB_SECTOR_CDE IN ('1700',
                         '1602')
  AND CUSTOMER_CDE IN
    (SELECT CUSTOMER_CDE
     FROM DW_ANALYTICS.DW_EB_TRANSACTION_FCT
     WHERE TXN_STATUS = 'SUC'
       AND TXN_DT < ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -12)
       AND TXN_DT >= ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -36)
       AND CUSTOMER_CDE IS NOT NULL)
  AND CUSTOMER_CDE NOT IN
    (SELECT CUSTOMER_CDE
     FROM DW_ANALYTICS.DW_EB_TRANSACTION_FCT
     WHERE TXN_STATUS = 'SUC'
       AND TXN_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')
       AND TXN_DT >= ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -12)
       AND CUSTOMER_CDE IS NOT NULL);

/*
Feature Name: EB_SACOMPAY_DAY_SINCE_LTST_TXN
Derived From: DW_EWALL_TRANSACTION_FCT
*/
INSERT INTO {TBL_NM}
SELECT CUSTOMER_CDE,
       'EB_SACOMPAY_DAY_SINCE_LTST_TXN' FTR_NM,
                                        TO_DATE('{RPT_DT}', 'DD-MM-YY') - NVL(MAX(PROCESS_DT), ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -36)) FTR_VAL,
                                        TO_CHAR(TO_DATE('{RPT_DT}', 'DD-MM-YY'), 'DD-MM-YYYY') AS RPT_DT,
                                        CURRENT_TIMESTAMP ADD_TSTP
FROM DW_ANALYTICS.DW_EWALL_TRANSACTION_FCT
WHERE PROCESS_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')
  AND PROCESS_DT >= ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -36)
  AND TXN_STATUS = 'S'
  AND CUSTOMER_CDE IN
    (SELECT CUSTOMER_CDE
     FROM CINS_TMP_CUST_TEST)
GROUP BY CUSTOMER_CDE;

/*
Feature Name: EB_SACOMPAY_SUM_TXN_AMT_1M, EB_SACOMPAY_SUM_TXN_AMT_3M, EB_SACOMPAY_SUM_TXN_AMT_6M
Derived From: DW_EWALL_TRANSACTION_FCT
*/
INSERT INTO {TBL_NM}
SELECT CUSTOMER_CDE,
       'EB_SACOMPAY_SUM_TXN_AMT_1M' FTR_NM,
                                    NVL(SUM((TO_AMT)), 0) FTR_VAL,
                                    TO_CHAR(TO_DATE('{RPT_DT}', 'DD-MM-YY'), 'DD-MM-YYYY') AS RPT_DT,
                                    CURRENT_TIMESTAMP ADD_TSTP
FROM
  (SELECT DISTINCT TXN_ID,
                   CUSTOMER_CDE,
                   PROCESS_DT,
                   ABS(TO_AMT) TO_AMT
   FROM DW_ANALYTICS.DW_EWALL_TRANSACTION_FCT
   WHERE PROCESS_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')
     AND PROCESS_DT >= ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -1)
     AND TXN_STATUS = 'S'
     AND CUSTOMER_CDE IN
       (SELECT CUSTOMER_CDE
        FROM CINS_TMP_CUST_TEST) ) TXN
GROUP BY CUSTOMER_CDE
UNION ALL
SELECT CUSTOMER_CDE,
       'EB_SACOMPAY_SUM_TXN_AMT_3M' FTR_NM,
                                    NVL(SUM((TO_AMT)), 0) FTR_VAL,
                                    TO_CHAR(TO_DATE('{RPT_DT}', 'DD-MM-YY'), 'DD-MM-YYYY') AS RPT_DT,
                                    CURRENT_TIMESTAMP ADD_TSTP
FROM
  (SELECT DISTINCT TXN_ID,
                   CUSTOMER_CDE,
                   PROCESS_DT,
                   ABS(TO_AMT) TO_AMT
   FROM DW_ANALYTICS.DW_EWALL_TRANSACTION_FCT
   WHERE PROCESS_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')
     AND PROCESS_DT >= ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -3)
     AND TXN_STATUS = 'S'
     AND CUSTOMER_CDE IN
       (SELECT CUSTOMER_CDE
        FROM CINS_TMP_CUST_TEST) ) TXN
GROUP BY CUSTOMER_CDE
UNION ALL
SELECT CUSTOMER_CDE,
       'EB_SACOMPAY_SUM_TXN_AMT_6M' FTR_NM,
                                    NVL(SUM((TO_AMT)), 0) FTR_VAL,
                                    TO_CHAR(TO_DATE('{RPT_DT}', 'DD-MM-YY'), 'DD-MM-YYYY') AS RPT_DT,
                                    CURRENT_TIMESTAMP ADD_TSTP
FROM
  (SELECT DISTINCT TXN_ID,
                   CUSTOMER_CDE,
                   PROCESS_DT,
                   ABS(TO_AMT) TO_AMT
   FROM DW_ANALYTICS.DW_EWALL_TRANSACTION_FCT
   WHERE PROCESS_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')
     AND PROCESS_DT >= ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -6)
     AND TXN_STATUS = 'S'
     AND CUSTOMER_CDE IN
       (SELECT CUSTOMER_CDE
        FROM CINS_TMP_CUST_TEST) ) TXN
GROUP BY CUSTOMER_CDE;

/*
Feature Name: EB_SACOMPAY_CT_TXN_1M, EB_SACOMPAY_CT_TXN_3M, EB_SACOMPAY_CT_TXN_6M
Derived From: DW_EWALL_TRANSACTION_FCT
*/
INSERT INTO {TBL_NM}
SELECT CUSTOMER_CDE,
       'EB_SACOMPAY_CT_TXN_1M' FTR_NM,
                               COUNT(DISTINCT TXN_ID) FTR_VAL,
                               TO_CHAR(TO_DATE('{RPT_DT}', 'DD-MM-YY'), 'DD-MM-YYYY') AS RPT_DT,
                               CURRENT_TIMESTAMP ADD_TSTP
FROM DW_ANALYTICS.DW_EWALL_TRANSACTION_FCT
WHERE PROCESS_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')
  AND PROCESS_DT >= ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -1)
  AND TXN_STATUS = 'S'
  AND CUSTOMER_CDE IN
    (SELECT CUSTOMER_CDE
     FROM CINS_TMP_CUST_TEST)
GROUP BY CUSTOMER_CDE
UNION ALL
SELECT CUSTOMER_CDE,
       'EB_SACOMPAY_CT_TXN_3M' FTR_NM,
                               COUNT(DISTINCT TXN_ID) FTR_VAL,
                               TO_CHAR(TO_DATE('{RPT_DT}', 'DD-MM-YY'), 'DD-MM-YYYY') AS RPT_DT,
                               CURRENT_TIMESTAMP ADD_TSTP
FROM DW_ANALYTICS.DW_EWALL_TRANSACTION_FCT
WHERE PROCESS_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')
  AND PROCESS_DT >= ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -3)
  AND TXN_STATUS = 'S'
  AND CUSTOMER_CDE IN
    (SELECT CUSTOMER_CDE
     FROM CINS_TMP_CUST_TEST)
GROUP BY CUSTOMER_CDE
UNION ALL
SELECT CUSTOMER_CDE,
       'EB_SACOMPAY_CT_TXN_6M' FTR_NM,
                               COUNT(DISTINCT TXN_ID) FTR_VAL,
                               TO_CHAR(TO_DATE('{RPT_DT}', 'DD-MM-YY'), 'DD-MM-YYYY') AS RPT_DT,
                               CURRENT_TIMESTAMP ADD_TSTP
FROM DW_ANALYTICS.DW_EWALL_TRANSACTION_FCT
WHERE PROCESS_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')
  AND PROCESS_DT >= ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -6)
  AND TXN_STATUS = 'S'
  AND CUSTOMER_CDE IN
    (SELECT CUSTOMER_CDE
     FROM CINS_TMP_CUST_TEST)
GROUP BY CUSTOMER_CDE;

/*
Feature Name: EB_SACOMPAY_CT_INACTIVE
Derived From: DW_EWALL_TRANSACTION_FCT
*/
INSERT INTO {TBL_NM}
SELECT CUSTOMER_CDE,
       'EB_SACOMPAY_CT_INACTIVE' FTR_NM,
                                 COUNT(*) FTR_VAL,
                                 TO_CHAR(TO_DATE('{RPT_DT}', 'DD-MM-YY'), 'DD-MM-YYYY') AS RPT_DT,
                                 CURRENT_TIMESTAMP ADD_TSTP
FROM
  (SELECT CUSTOMER_CDE,
          NVL(MONTHS_BETWEEN(LEAD(TXN_DT) OVER (PARTITION BY CUSTOMER_CDE
                                                ORDER BY TXN_DT), TXN_DT), MONTHS_BETWEEN(TO_DATE('{RPT_DT}', 'DD-MM-YY'), TXN_DT)) TXN_GAP
   FROM DW_ANALYTICS.DW_EWALL_TRANSACTION_FCT
   WHERE TXN_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')
     AND TXN_STATUS = 'S'
     AND CUSTOMER_CDE IN
       (SELECT CUSTOMER_CDE
        FROM CINS_TMP_CUST_TEST)
   UNION ALL SELECT B.CUSTOMER_CDE,
                    MONTHS_BETWEEN(MIN(TXN_DT), MAX(IDENTIFY_DT)) TXN_GAP
   FROM DW_ANALYTICS.DW_EWALL_TRANSACTION_FCT A
   JOIN DW_ANALYTICS.DW_EWALL_USER_DIM B ON A.CUSTOMER_CDE = B.CUSTOMER_CDE
   WHERE TXN_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')
     AND TXN_STATUS = 'S'
     AND TXN_DT > IDENTIFY_DT
     AND B.CUSTOMER_CDE IN
       (SELECT CUSTOMER_CDE
        FROM CINS_TMP_CUST_TEST)
   GROUP BY B.CUSTOMER_CDE)
WHERE TXN_GAP > 12
  AND TXN_GAP <= 36
GROUP BY CUSTOMER_CDE;

/*
Feature Name: EB_SACOMPAY_INACTIVE
Derived From: DW_EWALL_TRANSACTION_FCT
*/
INSERT INTO {TBL_NM}
SELECT CUSTOMER_CDE,
       'EB_SACOMPAY_INACTIVE' FTR_NM,
                              1 FTR_VAL,
                              TO_CHAR(TO_DATE('{RPT_DT}', 'DD-MM-YY'), 'DD-MM-YYYY') AS RPT_DT,
                              CURRENT_TIMESTAMP ADD_TSTP
FROM DW_ANALYTICS.DW_CUSTOMER_DIM
WHERE ACTIVE = 1
  AND COMPANY_KEY = 1
  AND SUB_SECTOR_CDE IN ('1700',
                         '1602')
  AND CUSTOMER_CDE IN
    (SELECT CUSTOMER_CDE
     FROM DW_ANALYTICS.DW_EWALL_TRANSACTION_FCT
     WHERE TXN_STATUS = 'S'
       AND TXN_DT < ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -12)
       AND TXN_DT >= ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -36)
       AND CUSTOMER_CDE IS NOT NULL)
  AND CUSTOMER_CDE NOT IN
    (SELECT CUSTOMER_CDE
     FROM DW_ANALYTICS.DW_EWALL_TRANSACTION_FCT
     WHERE TXN_STATUS = 'S'
       AND TXN_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')
       AND TXN_DT >= ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -12)
       AND CUSTOMER_CDE IS NOT NULL);

/*
Feature Name: EB_SACOMPAY_SUM_TXN_AMT_1M, EB_SACOMPAY_SUM_TXN_AMT_3M, EB_SACOMPAY_SUM_TXN_AMT_6M
Derived From: DW_EWALL_TRANSACTION_FCT
*/
INSERT INTO {TBL_NM}
SELECT CUSTOMER_CDE,
       'CARD_CREDIT_DAY_SINCE_LTST_TXN' FTR_NM,
                                        TO_DATE('{RPT_DT}', 'DD-MM-YY') - NVL(MAX(PROCESS_DT), ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -36)) FTR_VAL,
                                        TO_CHAR(TO_DATE('{RPT_DT}', 'DD-MM-YY'), 'DD-MM-YYYY') AS RPT_DT,
                                        CURRENT_TIMESTAMP ADD_TSTP
FROM DW_ANALYTICS.DW_CARD_TRANSACTION_FCT
WHERE PROCESS_DT >= ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -36)
  AND CARD_CDE LIKE '3%'
  AND TRAN_STATUS = 'S'
  AND POST_DT IS NOT NULL
  AND (MCC_CDE NOT IN (0,
                       6010,
                       6011,
                       6012,
                       4829,
                       6051)
       AND MCC_CDE IS NOT NULL
       OR MCC_CDE IN (6010,
                      6011,
                      6211,
                      6012,
                      6051))
  AND ACQUIRER_REFNO NOT LIKE '% %'
  AND PROCESS_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')
  AND CUSTOMER_CDE IN
    (SELECT CUSTOMER_CDE
     FROM DW_ANALYTICS.DW_CUSTOMER_DIM
     WHERE ACTIVE = 1
       AND COMPANY_KEY = 1
       AND SUB_SECTOR_CDE IN ('1700',
                              '1602'))
GROUP BY CUSTOMER_CDE;


/*
Feature Name: CARD_CREDIT_SUM_TXN_AMT_1M, CARD_CREDIT_SUM_TXN_AMT_3M, CARD_CREDIT_SUM_TXN_AMT_6M, CARD_CREDIT_SUM_TXN_AMT_12M
Derived From: DW_CARD_TRANSACTION_FCT
*/
INSERT INTO {TBL_NM}
SELECT CUSTOMER_CDE,
       'CARD_CREDIT_SUM_TXN_AMT_1M' FTR_NM,
                                    NVL(SUM(ABS(AMT_BILL)), 0) FTR_VAL,
                                    TO_CHAR(TO_DATE('{RPT_DT}', 'DD-MM-YY'), 'DD-MM-YYYY') AS RPT_DT,
                                    CURRENT_TIMESTAMP ADD_TSTP
FROM CINS_TMP_CREDIT_CARD_TRANSACTION_TEST
WHERE PROCESS_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')
  AND PROCESS_DT >= ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -1)
GROUP BY CUSTOMER_CDE
UNION ALL
SELECT CUSTOMER_CDE,
       'CARD_CREDIT_SUM_TXN_AMT_3M' FTR_NM,
                                    NVL(SUM(ABS(AMT_BILL)), 0) FTR_VAL,
                                    TO_CHAR(TO_DATE('{RPT_DT}', 'DD-MM-YY'), 'DD-MM-YYYY') AS RPT_DT,
                                    CURRENT_TIMESTAMP ADD_TSTP
FROM CINS_TMP_CREDIT_CARD_TRANSACTION_TEST
WHERE PROCESS_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')
  AND PROCESS_DT >= ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -3)
GROUP BY CUSTOMER_CDE
UNION ALL
SELECT CUSTOMER_CDE,
       'CARD_CREDIT_SUM_TXN_AMT_6M' FTR_NM,
                                    NVL(SUM(ABS(AMT_BILL)), 0) FTR_VAL,
                                    TO_CHAR(TO_DATE('{RPT_DT}', 'DD-MM-YY'), 'DD-MM-YYYY') AS RPT_DT,
                                    CURRENT_TIMESTAMP ADD_TSTP
FROM CINS_TMP_CREDIT_CARD_TRANSACTION_TEST
WHERE PROCESS_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')
  AND PROCESS_DT >= ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -6)
GROUP BY CUSTOMER_CDE
UNION ALL
SELECT CUSTOMER_CDE,
       'CARD_CREDIT_SUM_TXN_AMT_12M' FTR_NM,
                                     NVL(SUM(ABS(AMT_BILL)), 0) FTR_VAL,
                                     TO_CHAR(TO_DATE('{RPT_DT}', 'DD-MM-YY'), 'DD-MM-YYYY') AS RPT_DT,
                                     CURRENT_TIMESTAMP ADD_TSTP
FROM CINS_TMP_CREDIT_CARD_TRANSACTION_TEST
WHERE PROCESS_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')
  AND PROCESS_DT >= ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -12)
GROUP BY CUSTOMER_CDE;


/*
Feature Name: CARD_CREDIT_CT_TXN_1M, CARD_CREDIT_CT_TXN_3M, CARD_CREDIT_CT_TXN_6M, CARD_CREDIT_CT_TXN_12M
Derived From: DW_CARD_TRANSACTION_FCT
*/
INSERT INTO {TBL_NM}
SELECT CUSTOMER_CDE,
       'CARD_CREDIT_CT_TXN_1M' FTR_NM,
                               COUNT(*) FTR_VAL,
                               TO_CHAR(TO_DATE('{RPT_DT}', 'DD-MM-YY'), 'DD-MM-YYYY') AS RPT_DT,
                               CURRENT_TIMESTAMP ADD_TSTP
FROM CINS_TMP_CREDIT_CARD_TRANSACTION_TEST
WHERE PROCESS_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')
  AND PROCESS_DT >= ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -1)
GROUP BY CUSTOMER_CDE
UNION ALL
SELECT CUSTOMER_CDE,
       'CARD_CREDIT_CT_TXN_3M' FTR_NM,
                               COUNT(*) FTR_VAL,
                               TO_CHAR(TO_DATE('{RPT_DT}', 'DD-MM-YY'), 'DD-MM-YYYY') AS RPT_DT,
                               CURRENT_TIMESTAMP ADD_TSTP
FROM CINS_TMP_CREDIT_CARD_TRANSACTION_TEST
WHERE PROCESS_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')
  AND PROCESS_DT >= ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -3)
GROUP BY CUSTOMER_CDE
UNION ALL
SELECT CUSTOMER_CDE,
       'CARD_CREDIT_CT_TXN_6M' FTR_NM,
                               COUNT(*) FTR_VAL,
                               TO_CHAR(TO_DATE('{RPT_DT}', 'DD-MM-YY'), 'DD-MM-YYYY') AS RPT_DT,
                               CURRENT_TIMESTAMP ADD_TSTP
FROM CINS_TMP_CREDIT_CARD_TRANSACTION_TEST
WHERE PROCESS_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')
  AND PROCESS_DT >= ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -6)
GROUP BY CUSTOMER_CDE
UNION ALL
SELECT CUSTOMER_CDE,
       'CARD_CREDIT_CT_TXN_12M' FTR_NM,
                                COUNT(*) FTR_VAL,
                                TO_CHAR(TO_DATE('{RPT_DT}', 'DD-MM-YY'), 'DD-MM-YYYY') AS RPT_DT,
                                CURRENT_TIMESTAMP ADD_TSTP
FROM CINS_TMP_CREDIT_CARD_TRANSACTION_TEST
WHERE PROCESS_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')
  AND PROCESS_DT >= ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -12)
GROUP BY CUSTOMER_CDE;

/*
Feature Name: CARD_CREDIT_SUM_REV_CASH_1M, CARD_CREDIT_SUM_REV_CASH_3M, CARD_CREDIT_SUM_REV_CASH_6M, CARD_CREDIT_SUM_REV_CASH_12M
Derived From: DW_CARD_TRANSACTION_FCT
*/
INSERT INTO {TBL_NM}
SELECT CUSTOMER_CDE,
       'CARD_CREDIT_SUM_REV_CASH_1M' FTR_NM,
                                     NVL(SUM(ABS(AMT_BILL)), 0) FTR_VAL,
                                     TO_CHAR(TO_DATE('{RPT_DT}', 'DD-MM-YY'), 'DD-MM-YYYY') AS RPT_DT,
                                     CURRENT_TIMESTAMP ADD_TSTP
FROM CINS_TMP_CREDIT_CARD_TRANSACTION_TEST
WHERE PROCESS_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')
  AND PROCESS_DT >= ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -1)
  AND MCC_CDE IN ('6010',
                  '6011',
                  '6211',
                  '6012',
                  '6051')
GROUP BY CUSTOMER_CDE
UNION ALL
SELECT CUSTOMER_CDE,
       'CARD_CREDIT_SUM_REV_CASH_3M' FTR_NM,
                                     NVL(SUM(ABS(AMT_BILL)), 0) FTR_VAL,
                                     TO_CHAR(TO_DATE('{RPT_DT}', 'DD-MM-YY'), 'DD-MM-YYYY') AS RPT_DT,
                                     CURRENT_TIMESTAMP ADD_TSTP
FROM CINS_TMP_CREDIT_CARD_TRANSACTION_TEST
WHERE PROCESS_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')
  AND PROCESS_DT >= ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -3)
  AND MCC_CDE IN ('6010',
                  '6011',
                  '6211',
                  '6012',
                  '6051')
GROUP BY CUSTOMER_CDE
UNION ALL
SELECT CUSTOMER_CDE,
       'CARD_CREDIT_SUM_REV_CASH_6M' FTR_NM,
                                     NVL(SUM(ABS(AMT_BILL)), 0) FTR_VAL,
                                     TO_CHAR(TO_DATE('{RPT_DT}', 'DD-MM-YY'), 'DD-MM-YYYY') AS RPT_DT,
                                     CURRENT_TIMESTAMP ADD_TSTP
FROM CINS_TMP_CREDIT_CARD_TRANSACTION_TEST
WHERE PROCESS_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')
  AND PROCESS_DT >= ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -6)
  AND MCC_CDE IN ('6010',
                  '6011',
                  '6211',
                  '6012',
                  '6051')
GROUP BY CUSTOMER_CDE
UNION ALL
SELECT CUSTOMER_CDE,
       'CARD_CREDIT_SUM_REV_CASH_12M' FTR_NM,
                                      NVL(SUM(ABS(AMT_BILL)), 0) FTR_VAL,
                                      TO_CHAR(TO_DATE('{RPT_DT}', 'DD-MM-YY'), 'DD-MM-YYYY') AS RPT_DT,
                                      CURRENT_TIMESTAMP ADD_TSTP
FROM CINS_TMP_CREDIT_CARD_TRANSACTION_TEST
WHERE PROCESS_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')
  AND PROCESS_DT >= ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -12)
  AND MCC_CDE IN ('6010',
                  '6011',
                  '6211',
                  '6012',
                  '6051')
GROUP BY CUSTOMER_CDE;


/*
Feature Name: CARD_CREDIT_SUM_REV_SALE_1M, CARD_CREDIT_SUM_REV_SALE_3M, CARD_CREDIT_SUM_REV_SALE_6M, CARD_CREDIT_SUM_REV_SALE_12M
Derived From: DW_CARD_TRANSACTION_FCT
*/
INSERT INTO {TBL_NM}
SELECT CUSTOMER_CDE,
       'CARD_CREDIT_SUM_REV_SALE_1M' FTR_NM,
                                     NVL(SUM(ABS(AMT_BILL)), 0) FTR_VAL,
                                     TO_CHAR(TO_DATE('{RPT_DT}', 'DD-MM-YY'), 'DD-MM-YYYY') AS RPT_DT,
                                     CURRENT_TIMESTAMP ADD_TSTP
FROM CINS_TMP_CREDIT_CARD_TRANSACTION_TEST
WHERE PROCESS_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')
  AND PROCESS_DT >= ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -1)
  AND MCC_CDE NOT IN (0,
                      6010,
                      6011,
                      6012,
                      4829,
                      6051)
  AND MCC_CDE IS NOT NULL
GROUP BY CUSTOMER_CDE
UNION ALL
SELECT CUSTOMER_CDE,
       'CARD_CREDIT_SUM_REV_SALE_3M' FTR_NM,
                                     NVL(SUM(ABS(AMT_BILL)), 0) FTR_VAL,
                                     TO_CHAR(TO_DATE('{RPT_DT}', 'DD-MM-YY'), 'DD-MM-YYYY') AS RPT_DT,
                                     CURRENT_TIMESTAMP ADD_TSTP
FROM CINS_TMP_CREDIT_CARD_TRANSACTION_TEST
WHERE PROCESS_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')
  AND PROCESS_DT >= ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -3)
  AND MCC_CDE NOT IN (0,
                      6010,
                      6011,
                      6012,
                      4829,
                      6051)
  AND MCC_CDE IS NOT NULL
GROUP BY CUSTOMER_CDE
UNION ALL
SELECT CUSTOMER_CDE,
       'CARD_CREDIT_SUM_REV_SALE_6M' FTR_NM,
                                     NVL(SUM(ABS(AMT_BILL)), 0) FTR_VAL,
                                     TO_CHAR(TO_DATE('{RPT_DT}', 'DD-MM-YY'), 'DD-MM-YYYY') AS RPT_DT,
                                     CURRENT_TIMESTAMP ADD_TSTP
FROM CINS_TMP_CREDIT_CARD_TRANSACTION_TEST
WHERE PROCESS_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')
  AND PROCESS_DT >= ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -6)
  AND MCC_CDE NOT IN (0,
                      6010,
                      6011,
                      6012,
                      4829,
                      6051)
  AND MCC_CDE IS NOT NULL
GROUP BY CUSTOMER_CDE
UNION ALL
SELECT CUSTOMER_CDE,
       'CARD_CREDIT_SUM_REV_SALE_12M' FTR_NM,
                                      NVL(SUM(ABS(AMT_BILL)), 0) FTR_VAL,
                                      TO_CHAR(TO_DATE('{RPT_DT}', 'DD-MM-YY'), 'DD-MM-YYYY') AS RPT_DT,
                                      CURRENT_TIMESTAMP ADD_TSTP
FROM CINS_TMP_CREDIT_CARD_TRANSACTION_TEST
WHERE PROCESS_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')
  AND PROCESS_DT >= ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -12)
  AND MCC_CDE NOT IN (0,
                      6010,
                      6011,
                      6012,
                      4829,
                      6051)
  AND MCC_CDE IS NOT NULL
GROUP BY CUSTOMER_CDE;

/*
Feature Name: CARD_CREDIT_SUM_BAL_NOW
Derived From: DW_CARD_TRANSACTION_FCT
*/
INSERT INTO {TBL_NM}
SELECT CUSTOMER_CDE,
       'CARD_CREDIT_SUM_BAL_NOW' FTR_NM,
                                 SUM(TT_ORIGINAL_BALANCE) FTR_VAL,
                                 TO_CHAR(TO_DATE('{RPT_DT}', 'DD-MM-YY'), 'DD-MM-YYYY') AS RPT_DT,
                                 CURRENT_TIMESTAMP ADD_TSTP
FROM
  (SELECT BAL.*,
          ROW_NUMBER() OVER(PARTITION BY CUSTOMER_CDE, CARD_CDE
                            ORDER BY PROCESS_DT DESC) RN
   FROM
     (SELECT CUSTOMER_CDE,
             CARD_CDE,
             TT_ORIGINAL_BALANCE,
             PROCESS_DT
      FROM DW_ANALYTICS.DATA_RPT_CARD_493 CC
      WHERE PROCESS_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')
        AND CUSTOMER_CDE IN
          (SELECT CUSTOMER_CDE
           FROM CINS_TMP_CUST_TEST)
        AND CARD_CDE LIKE '3%' ) BAL) BAL
WHERE RN = 1
GROUP BY CUSTOMER_CDE;


/*
Feature Name: CARD_CREDIT_CT_CARD_ACTIVE
Derived From: DW_CARD_TRANSACTION_FCT
*/
INSERT INTO {TBL_NM}
SELECT CUSTOMER_CDE,
       'CARD_CREDIT_CT_CARD_ACTIVE' FTR_NM,
                                    COUNT(DISTINCT CARD_CDE) FTR_VAL,
                                    TO_CHAR(TO_DATE('{RPT_DT}', 'DD-MM-YY'), 'DD-MM-YYYY') AS RPT_DT,
                                    CURRENT_TIMESTAMP ADD_TSTP
FROM DW_ANALYTICS.DW_CARD_MASTER_DIM DIM
WHERE ACTIVE = 1
  AND CARD_CDE LIKE '3%'
  AND CUSTOMER_CDE IN
    (SELECT CUSTOMER_CDE
     FROM CINS_TMP_CUST_TEST)
  AND EXISTS
    (SELECT CUSTOMER_CDE,
            CARD_CDE
     FROM DW_ANALYTICS.DW_CARD_TRANSACTION_FCT FCT
     WHERE DIM.CUSTOMER_CDE = FCT.CUSTOMER_CDE
       AND DIM.CARD_CDE = FCT.CARD_CDE
       AND CARD_CDE LIKE '3%'
       AND TRAN_STATUS = 'S'
       AND POST_DT IS NOT NULL
       AND (MCC_CDE NOT IN (0,
                            6010,
                            6011,
                            6012,
                            4829,
                            6051)
            AND MCC_CDE IS NOT NULL
            OR MCC_CDE IN (6010,
                           6011,
                           6211,
                           6012,
                           6051))
       AND PROCESS_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')
       AND PROCESS_DT >= ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -12))
GROUP BY CUSTOMER_CDE;


/*
Feature Name: CARD_CREDIT_CT_INACTIVE_ALL
Derived From: CINS_TMP_CREDIT_CARD_TRANSACTION_TEST
*/
INSERT INTO {TBL_NM}
SELECT CUSTOMER_CDE,
       'CARD_CREDIT_CT_INACTIVE_ALL' FTR_NM,
                                     COUNT(*) FTR_VAL,
                                     TO_CHAR(TO_DATE('{RPT_DT}', 'DD-MM-YY'), 'DD-MM-YYYY') AS RPT_DT,
                                     CURRENT_TIMESTAMP ADD_TSTP
FROM
  (SELECT CUSTOMER_CDE,
          NVL(MONTHS_BETWEEN(LEAD(PROCESS_DT) OVER (PARTITION BY CUSTOMER_CDE
                                                    ORDER BY PROCESS_DT), PROCESS_DT), MONTHS_BETWEEN(TO_DATE('{RPT_DT}', 'DD-MM-YY'), PROCESS_DT)) TXN_GAP
   FROM CINS_TMP_CREDIT_CARD_TRANSACTION_TEST
   WHERE PROCESS_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY'))
WHERE TXN_GAP > 3
GROUP BY CUSTOMER_CDE;


/*
Feature Name: CARD_CREDIT_INACTIVE
Derived From: DW_CARD_TRANSACTION_FCT
*/
INSERT INTO {TBL_NM}
SELECT CUSTOMER_CDE,
       'CARD_CREDIT_INACTIVE' FTR_NM,
                              1 FTR_VAL,
                              TO_CHAR(TO_DATE('{RPT_DT}', 'DD-MM-YY'), 'DD-MM-YYYY') AS RPT_DT,
                              CURRENT_TIMESTAMP ADD_TSTP
FROM DW_ANALYTICS.DW_CUSTOMER_DIM
WHERE ACTIVE = 1
  AND COMPANY_KEY = 1
  AND SUB_SECTOR_CDE IN ('1700',
                         '1602')
  AND CUSTOMER_CDE IN
    (SELECT CUSTOMER_CDE
     FROM DW_ANALYTICS.DW_CARD_MASTER_DIM
     WHERE CARD_CDE LIKE '3%'
       AND STATUS_CDE = ' '
       AND ACTIVATION_DT < ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -3)
       AND TO_CHAR(ACTIVATION_DT, 'yyyy') > 1900)
  AND CUSTOMER_CDE NOT IN
    (SELECT CUSTOMER_CDE
     FROM DW_ANALYTICS.DW_CARD_TRANSACTION_FCT
     WHERE CARD_CDE LIKE '3%'
       AND TRAN_STATUS = 'S'
       AND POST_DT IS NOT NULL
       AND MCC_CDE NOT IN (0,
                           4829)
       AND MCC_CDE IS NOT NULL
       AND PROCESS_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')
       AND PROCESS_DT >= ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -3));


/*
Feature Name: CASA_CT_ACCT_ACTIVE
Derived From: DW_ACCOUNT_MASTER_DIM, DWA_STMT_EBANK, TRANSACTION_CODE
*/
INSERT INTO {TBL_NM}
SELECT CUSTOMER_CDE,
       'CASA_CT_ACCT_ACTIVE' FTR_NM,
                             COUNT(DISTINCT ACCT_ID) FTR_VAL,
                             TO_CHAR(TO_DATE('{RPT_DT}', 'DD-MM-YY'), 'DD-MM-YYYY') AS RPT_DT,
                             CURRENT_TIMESTAMP ADD_TSTP
FROM DW_ANALYTICS.DW_ACCOUNT_MASTER_DIM DIM
WHERE ACTIVE = 1
  AND EXISTS
    (SELECT CUSTOMER_ID
     FROM DW_ANALYTICS.DWA_STMT_EBANK FCT
     JOIN
       (SELECT TRANSACTION_CODE
        FROM DW_ANALYTICS.TRANSACTION_CODE
        WHERE INITIATION = 'CUSTOMER') TC ON FCT.TRANSACTION_CODE = TC.TRANSACTION_CODE
     WHERE DIM.CUSTOMER_CDE = FCT.CUSTOMER_ID
       AND PRODUCT_CATEGORY LIKE '10__'
       AND CUSTOMER_ID IN
         (SELECT CUSTOMER_CDE
          FROM CINS_TMP_CUST_TEST)
       AND DIM.ACCT_ID = FCT.ACCOUNT_NUMBER
       AND PROCESS_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')
       AND PROCESS_DT >= ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -12) )
GROUP BY CUSTOMER_CDE;


/*
Feature Name: CASA_CT_TXN_1M, CASA_CT_TXN_3M, CASA_CT_TXN_6M, CASA_CT_TXN_12M
Derived From: DWA_STMT_EBANK, TRANSACTION_CODE
*/
INSERT INTO {TBL_NM}
SELECT CUSTOMER_ID CUSTOMER_CDE,
       'CASA_CT_TXN_1M' FTR_NM,
                        COUNT(STMT_ENTRY_ID) FTR_VAL,
                        TO_CHAR(TO_DATE('{RPT_DT}', 'DD-MM-YY'), 'DD-MM-YYYY') AS RPT_DT,
                        CURRENT_TIMESTAMP ADD_TSTP
FROM DW_ANALYTICS.DWA_STMT_EBANK TXN
JOIN
  (SELECT TRANSACTION_CODE
   FROM DW_ANALYTICS.TRANSACTION_CODE
   WHERE INITIATION = 'CUSTOMER') TC ON TXN.TRANSACTION_CODE = TC.TRANSACTION_CODE
WHERE PRODUCT_CATEGORY LIKE '10__'
  AND PROCESS_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')
  AND PROCESS_DT >= ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -1)
  AND CUSTOMER_ID IN
    (SELECT CUSTOMER_CDE
     FROM CINS_TMP_CUST_TEST)
GROUP BY CUSTOMER_ID
UNION ALL
SELECT CUSTOMER_ID CUSTOMER_CDE,
       'CASA_CT_TXN_3M' FTR_NM,
                        COUNT(STMT_ENTRY_ID) FTR_VAL,
                        TO_CHAR(TO_DATE('{RPT_DT}', 'DD-MM-YY'), 'DD-MM-YYYY') AS RPT_DT,
                        CURRENT_TIMESTAMP ADD_TSTP
FROM DW_ANALYTICS.DWA_STMT_EBANK TXN
JOIN
  (SELECT TRANSACTION_CODE
   FROM DW_ANALYTICS.TRANSACTION_CODE
   WHERE INITIATION = 'CUSTOMER') TC ON TXN.TRANSACTION_CODE = TC.TRANSACTION_CODE
WHERE PRODUCT_CATEGORY LIKE '10__'
  AND PROCESS_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')
  AND PROCESS_DT >= ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -3)
  AND CUSTOMER_ID IN
    (SELECT CUSTOMER_CDE
     FROM CINS_TMP_CUST_TEST)
GROUP BY CUSTOMER_ID
UNION ALL
SELECT CUSTOMER_ID CUSTOMER_CDE,
       'CASA_CT_TXN_6M' FTR_NM,
                        COUNT(STMT_ENTRY_ID) FTR_VAL,
                        TO_CHAR(TO_DATE('{RPT_DT}', 'DD-MM-YY'), 'DD-MM-YYYY') AS RPT_DT,
                        CURRENT_TIMESTAMP ADD_TSTP
FROM DW_ANALYTICS.DWA_STMT_EBANK TXN
JOIN
  (SELECT TRANSACTION_CODE
   FROM DW_ANALYTICS.TRANSACTION_CODE
   WHERE INITIATION = 'CUSTOMER') TC ON TXN.TRANSACTION_CODE = TC.TRANSACTION_CODE
WHERE PRODUCT_CATEGORY LIKE '10__'
  AND PROCESS_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')
  AND PROCESS_DT >= ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -6)
  AND CUSTOMER_ID IN
    (SELECT CUSTOMER_CDE
     FROM CINS_TMP_CUST_TEST)
GROUP BY CUSTOMER_ID
UNION ALL
SELECT CUSTOMER_ID CUSTOMER_CDE,
       'CASA_CT_TXN_12M' FTR_NM,
                         COUNT(STMT_ENTRY_ID) FTR_VAL,
                         TO_CHAR(TO_DATE('{RPT_DT}', 'DD-MM-YY'), 'DD-MM-YYYY') AS RPT_DT,
                         CURRENT_TIMESTAMP ADD_TSTP
FROM DW_ANALYTICS.DWA_STMT_EBANK TXN
JOIN
  (SELECT TRANSACTION_CODE
   FROM DW_ANALYTICS.TRANSACTION_CODE
   WHERE INITIATION = 'CUSTOMER') TC ON TXN.TRANSACTION_CODE = TC.TRANSACTION_CODE
WHERE PRODUCT_CATEGORY LIKE '10__'
  AND PROCESS_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')
  AND PROCESS_DT >= ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -12)
  AND CUSTOMER_ID IN
    (SELECT CUSTOMER_CDE
     FROM CINS_TMP_CUST_TEST)
GROUP BY CUSTOMER_ID;