/*
Table Name: CINS_TMP_CARD_DIM_{RPT_DT_TBL}
Derived From: 
  DW_ANALYTICS.DW_CARD_MASTER_DIM: 
    - CARD_CDE
    - STATUS_CDE
    - PLASTIC_CDE 
*/
INSERT INTO CINS_TMP_CARD_DIM_{RPT_DT_TBL} 
SELECT DISTINCT CARD_CDE 
FROM DW_ANALYTICS.DW_CARD_MASTER_DIM DIM
RIGHT JOIN CINS_TMP_CUSTOMER_{RPT_DT_TBL} C ON DIM.CUSTOMER_CDE=C.CUSTOMER_CDE
WHERE DIM.STATUS_CDE = ' ' 
    AND DIM.PLASTIC_CDE = ' ';