/*
Table Name: CINS_TMP_POS_MERCHANT_6M_{RPT_DT_TBL}
Derived From:
  DW_ANALYTICS.DW_CARD_TRANSACTION_FCT:
    - CUSTOMER_CDE
    - MERCHANT_CDE
    - CARDHDR_NO
    - APPROVAL_CDE
    - RETRVL_REFNO
    - PROCESS_DT
  DW_ANALYTICS.DW_CARD_MERCHANT_DIM:
    - MERCHANT_ID
*/
INSERT INTO CINS_TMP_POS_MERCHANT_6M_{RPT_DT_TBL}
WITH 
T1 AS (
  SELECT 
    CUSTOMER_CDE, 
    TRIM(' ' FROM(MERCHANT_CDE)) AS MERCHANT_CDE, 
    CARDHDR_NO,
    TRIM(' ' FROM (APPROVAL_CDE)) AS APPROVAL_CDE,
    RETRVL_REFNO,
    ABS(AMT_BILL) AS AMT_BILL,
    PROCESS_DT
  FROM DW_ANALYTICS.DW_CARD_TRANSACTION_FCT Ta1
  INNER JOIN CINS_TMP_CUSTOMER_{RPT_DT_TBL} Ta2 ON Ta1.CUSTOMER_CDE=Ta2.CUSTOMER_CDE
  WHERE 
    PROCESS_DT < TO_DATE('{RPT_DT}','DD-MM-YY') 
    AND PROCESS_DT >= ADD_MONTHS(TO_DATE('{RPT_DT}','DD-MM-YY'), -6)
    AND TRAN_STATUS = 'S' 
    AND Ta1.CUSTOMER_CDE IS NOT NULL
),
T2 AS (
  SELECT 
    CUSTOMER_CDE, 
    MERCHANT_CDE,
    CARDHDR_NO,
    APPROVAL_CDE, 
    RETRVL_REFNO,
    PROCESS_DT,
    AMT_BILL,
    ROW_NUMBER() OVER(PARTITION BY CUSTOMER_CDE, CARDHDR_NO, APPROVAL_CDE, RETRVL_REFNO ORDER BY PROCESS_DT DESC) AS RN
  FROM T1
),
T3 AS (
  SELECT 
    CUSTOMER_CDE, 
    MERCHANT_CDE,
    COUNT(*) AS CT_TXN_POS,
    SUM(AMT_BILL) AS AMT_BILL,
    ROW_NUMBER() OVER(PARTITION BY CUSTOMER_CDE ORDER BY COUNT(*) DESC) AS RN1
  FROM T2
  WHERE RN = 1
  GROUP BY CUSTOMER_CDE, MERCHANT_CDE
),
T4 AS (
  SELECT 
    CUSTOMER_CDE, 
    MERCHANT_CDE,  
    CT_TXN_POS,
    AMT_BILL
  FROM T3
  WHERE RN1 = 1
),
T5 AS (
  SELECT MERCHANT_ID
  FROM DW_ANALYTICS.DW_CARD_MERCHANT_DIM
),
T6 AS (
  SELECT 
    CUSTOMER_CDE, 
    MERCHANT_ID,
    NULL AS TERMINAL_ID,
    CT_TXN_POS,
    AMT_BILL,
    TO_CHAR(TO_DATE('{RPT_DT}','DD-MM-YY'), 'DD-MM-YYYY') AS RPT_DT, 
    CURRENT_TIMESTAMP AS ADD_TSTP  
  FROM T4
  JOIN T5 ON T4.MERCHANT_CDE = T5.MERCHANT_ID
  WHERE T4.MERCHANT_CDE IS NOT NULL
)

SELECT * FROM T6;