/*
Table Name: CINS_TMP_EB_MB_CROSSELL_{RPT_DT_TBL}
Derived From: 
    DW_ANALYTICS.DW_EB_USER:
        - CUSTOMER_CDE
        - LOGIN_ALLOWED
        - DEL_FLG
        - PROCESS_DT
        - CORP_ID
        - REC_UPDATE_DT
        - INPUT_DT
    CINS_TMP_CUSTOMER_{RPT_DT_TBL}:
        - CUSTOMER_CDE
*/
INSERT INTO CINS_TMP_EB_MB_CROSSELL_{RPT_DT_TBL} 
SELECT CUSTOMER_CDE, CORP_ID, INPUT_DT 
FROM (
    SELECT CUSTOMER_CDE, CORP_ID, INPUT_DT, ROW_NUMBER() OVER(PARTITION BY CUSTOMER_CDE, CORP_ID ORDER BY REC_UPDATE_DT DESC) RN 
    FROM DW_ANALYTICS.DW_EB_USER  
    WHERE CUSTOMER_CDE IN (SELECT CUSTOMER_CDE FROM CINS_TMP_CUSTOMER_{RPT_DT_TBL}) 
        AND LOGIN_ALLOWED NOT IN ('N') 
        AND DEL_FLG NOT IN ('N')
        AND PROCESS_DT = TO_DATE('{RPT_DT}', 'DD-MM-YY')
) 
WHERE RN = 1;