/*
Table Name: CINS_TMP_DATA_RPT_LOAN_{RPT_DT_TBL}
Derived From: 
    DW_ANALYTICS.DATA_RPT_CARD_493:
        - CUSTOMER_CDE
        - CARD_CDE
        - PROCESS_DT
        - TT_CARD_LIMIT
        - TT_LOAN_GROUP
        - COMPANY_KEY
    CINS_TMP_CUSTOMER_{RPT_DT_TBL}:
        - CUSTOMER_CDE
    CINS_TMP_CARD_DIM_{RPT_DT_TBL}:
        - CARD_CDE
*/
INSERT INTO CINS_TMP_DATA_RPT_LOAN_{RPT_DT_TBL}
SELECT 
    CUSTOMER_CDE, 
    MAX(TT_LOAN_GROUP) AS TT_LOAN_GROUP
FROM (
    SELECT 
        T.CUSTOMER_CDE,
        CAST(SUBSTR(T.TT_LOAN_GROUP,2,1) AS INT) TT_LOAN_GROUP
    FROM 
        DW_ANALYTICS.DATA_RPT_CARD_493 T
        JOIN CINS_TMP_CUSTOMER_{RPT_DT_TBL} C ON T.CUSTOMER_CDE=C.CUSTOMER_CDE
        JOIN CINS_TMP_CARD_DIM_{RPT_DT_TBL} D ON T.CARD_CDE=D.CARD_CDE
    WHERE 
        T.COMPANY_KEY = 1 
        AND SUBSTR(T.CARD_CDE,1,1) = '3'
        AND ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -6) <= T.PROCESS_DT 
        AND T.PROCESS_DT < TO_DATE('{RPT_DT}','DD-MM-YY')
)
GROUP BY CUSTOMER_CDE;