/*
Feature Name: CARD_AVG_BAL_6M
Derived From: DATA_RPT_CARD_493, CINS_TMP_CUSTOMER_{RPT_DT_TBL}
*/
INSERT INTO {TBL_NM}
SELECT CUSTOMER_CDE,
       'CARD_AVG_BAL_6M' FTR_NM,
                         AVG(ABS(TT_ORIGINAL_BALANCE)) FTR_VAL,
                         TO_DATE('{RPT_DT}', 'DD-MM-YY') AS RPT_DT,
                         CURRENT_TIMESTAMP ADD_TSTP
FROM DW_ANALYTICS.DATA_RPT_CARD_493
WHERE CUSTOMER_CDE IN
    (SELECT CUSTOMER_CDE
     FROM CINS_TMP_CUSTOMER_{RPT_DT_TBL})
  AND PROCESS_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')
  AND PROCESS_DT >= ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -6)
GROUP BY CUSTOMER_CDE