SRC_TBL: CINS_TMP_CUSTOMER
CASA:
  FEATURE:
    - CASA_ACCT_ACTIVE_CT_12M
    - CASA_DAY_SINCE_LAST_TXN_CT_36M
    - CASA_TXN_CT_1M
    - CASA_TXN_CT_3M
    - CASA_TXN_CT_6M
    - CASA_TXN_CT_12M
    - CASA_BAL_SUM_NOW
    - CASA_BAL_AVG_1M
    - CASA_BAL_MAX_1M
    - CASA_BAL_MIN_1M
    - CASA_TXN_AMT_SUM_1M
    - CASA_TXN_AMT_SUM_3M
    - CASA_TXN_AMT_SUM_6M
    - CASA_TXN_AMT_SUM_12M
  TABLE_NAME: CINS_FEATURE_STORE_CASA