/*
Feature Name: AREA_SPLIT
Derived From: DW_CUSTOMER_DIM, DW_ORG_LOCATION_DIM
*/
INSERT INTO {TBL_NM}
SELECT A.CUSTOMER_CDE,
       'AREA_SPLIT' FTR_NM,
                    B.AREA_NAME FTR_VAL,
                    TO_DATE('{RPT_DT}', 'DD-MM-YY') AS RPT_DT,
                    CURRENT_TIMESTAMP ADD_TSTP
FROM
  (SELECT CUSTOMER_CDE,
          SUB_BRANCH_KEY
   FROM DW_ANALYTICS.DW_CUSTOMER_DIM
   WHERE SUB_SECTOR_CDE IN ('1700',
                            '1602')
     AND ACTIVE = '1'
     AND COMPANY_KEY = '1'
     AND UPDATE_DT <= TO_DATE('{RPT_DT}', 'DD-MM-YY') )A
JOIN
  (SELECT *
   FROM DW_ANALYTICS.DW_ORG_LOCATION_DIM
   WHERE ACTIVE = '1'
     AND COMPANY_KEY = '1') B ON A.SUB_BRANCH_KEY = B.SUB_BRANCH_KEY