/*
Feature Name: CARD_CREDIT_UP_SELL_LABEL1_6M
Derived From: DW_CARD_MASTER_DIM
*/
INSERT INTO {TBL_NM}
SELECT CUSTOMER_CDE,
       'CARD_CREDIT_UP_SELL_LABEL1_6M' AS FTR_NM,
       FTR_VAL,
       TO_DATE('{RPT_DT}', 'DD-MM-YY') AS RPT_DT,
       CURRENT_TIMESTAMP AS ADD_TSTP
FROM
  (SELECT CUSTOMER_CDE,
          CASE
              WHEN REASON = 'UD' THEN 1
              ELSE 0
          END AS FTR_VAL,
          ROW_NUMBER() OVER(PARTITION BY CUSTOMER_CDE
                            ORDER BY UPDATE_DT DESC) RN
   FROM DW_ANALYTICS.DW_CARD_MASTER_DIM
   WHERE STATUS_CDE = ' '
     AND PLASTIC_CDE = ' ' )
WHERE RN = 1
  AND FTR_VAL = 1