/*
Feature Name: EB_MBIB_SUM_TXN_AMT_1M, EB_MBIB_SUM_TXN_AMT_3M, EB_MBIB_SUM_TXN_AMT_6M
Derived From: DW_EB_TRANSACTION_FCT, CINS_TMP_CUSTOMER_{RPT_DT_TBL}
*/
INSERT INTO {TBL_NM}
SELECT CUSTOMER_CDE,
       'EB_MBIB_SUM_TXN_AMT_1M' FTR_NM,
                                NVL(SUM(ABS(AMT_ENTRY_LCL)), 0) FTR_VAL,
                                TO_DATE('{RPT_DT}', 'DD-MM-YY') AS RPT_DT,
                                CURRENT_TIMESTAMP ADD_TSTP
FROM
  (SELECT DISTINCT TXN_ID,
                   CUSTOMER_CDE,
                   TXN_DT,
                   AMT_ENTRY_LCL
   FROM DW_ANALYTICS.DW_EB_TRANSACTION_FCT
   WHERE TXN_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')
     AND TXN_DT >= ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -1)
     AND TXN_STATUS = 'SUC'
     AND CUSTOMER_CDE IN
       (SELECT CUSTOMER_CDE
        FROM CINS_TMP_CUSTOMER_{RPT_DT_TBL}) ) TXN
GROUP BY CUSTOMER_CDE