RAW_FEATURE_NAMES = [
    'CASA_HOLD','CARD_CREDIT_HOLD','EB_SACOMPAY_HOLD','EB_MBIB_HOLD',
    'LOR','CREDIT_SCORE',
    'CASA_BAL_SUM_NOW',
    'CASA_DAY_SINCE_LAST_TXN_CT_36M',
    'CARD_CREDIT_MAX_LIMIT','CARD_CREDIT_SUM_BAL_NOW',
    'EB_SACOMPAY_DAY_SINCE_LTST_LOGIN',
    'EB_SACOMPAY_DAY_SINCE_LTST_TXN',
    'EB_MBIB_DAY_SINCE_ACTIVE',
    'LIFE_STG', 'AREA',
]

LABEL = 'REACTIVATED'