CREATE TABLE CINS_2M_PART (
    PRODUCT VARCHAR2(25 BYTE),
    CUSTOMER_CDE VARCHAR2(25 BYTE)
);


COMMIT;


CREATE TABLE CINS_TMP_LST_11062023 (
    PRODUCT VARCHAR(20), 
    CUSTOMER_CDE VARCHAR(20)
);


COMMIT;


/*
Table Name: CINS_2M_PART
Derived From: 
    DW_ANALYTICS.DWD_TOI_FCT: 
        - CUSTOMER_CDE
        - NII_DEPOSIT_MTH 
        - NII_LOAN_MTH 
        - NII_FEE_MTH 
        - NII_FX_MTH
        - PROCESS_DT
    DW_CUSTOMER_DIM:
        - ACTIVE
        - CUSTOMER_CDE
        - COMPANY_KEY
        - SUB_SECTOR_CDE
*/
INSERT INTO CINS_2M_PART
SELECT 'CARDS' PRODUCT, A.CUSTOMER_CDE 
FROM DW_ANALYTICS.DWA_CARD_TOI_FCT A
JOIN (
    SELECT CUSTOMER_CDE 
    FROM DW_ANALYTICS.DW_CUSTOMER_DIM
    WHERE ACTIVE = 1 
    AND COMPANY_KEY = 1 
    AND SUB_SECTOR_CDE IN ('1700', '1602')
) B 
ON A.CUSTOMER_CDE=B.CUSTOMER_CDE
WHERE TRUNC(A.PROCESS_DT) IN (
    '31-JAN-2022',
    '28-FEB-2022',
    '31-MAR-2022',
    '30-APR-2022',
    '31-MAY-2022',
    '30-JUN-2022',
    '31-JUL-2022',
    '31-AUG-2022',
    '30-SEP-2022',
    '31-OCT-2022',
    '30-NOV-2022',
    '31-DEC-2022'
)
GROUP BY A.CUSTOMER_CDE
HAVING SUM(A.NII_CARD_MTD)>=300000


COMMIT;


INSERT INTO CINS_2M_PART
SELECT 'OTHER' PRODUCT, A.CUSTOMER_CDE 
FROM (
    SELECT CUSTOMER_CDE, PROCESS_DT, (NII_DEPOSIT_MTH + NII_LOAN_MTH + NII_FEE_MTH + NII_FX_MTH) NII_CARD_MTD 
    FROM DW_ANALYTICS.DWD_TOI_FCT
) A
JOIN (
    SELECT CUSTOMER_CDE 
    FROM DW_ANALYTICS.DW_CUSTOMER_DIM
    WHERE ACTIVE = 1 
    AND COMPANY_KEY = 1 
    AND SUB_SECTOR_CDE IN ('1700', '1602')
) B 
ON A.CUSTOMER_CDE=B.CUSTOMER_CDE
WHERE TRUNC(A.PROCESS_DT) IN (
    '31-JAN-2022',
    '28-FEB-2022',
    '31-MAR-2022',
    '30-APR-2022',
    '31-MAY-2022',
    '30-JUN-2022',
    '31-JUL-2022',
    '31-AUG-2022',
    '30-SEP-2022',
    '31-OCT-2022',
    '30-NOV-2022',
    '31-DEC-2022'
)
GROUP BY A.CUSTOMER_CDE
HAVING SUM(A.NII_CARD_MTD)>=300000;


COMMIT;


/*
Table Name: CINS_TMP_LST_11062023
Derived From: 
    CINS_TMP_CREDIT_CARD_TRANSACTION_11062023: 
        - CUSTOMER_CDE
        - PROCESS_DT
    CINS_2M_PART:
        - PRODUCT
        - CUSTOMER_CDE
    DW_ANALYTICS.DW_EB_TRANSACTION_FCT:
        - CUSTOMER_CDE
        - TXN_DT
        - TXN_STATUS
    DW_ANALYTICS.DW_EWALL_TRANSACTION_FCT:
        - CUSTOMER_CDE
        - PROCESS_DT
        - TXN_STATUS
    DW_ANALYTICS.DWA_STMT_EBANK:
        - CUSTOMER_ID
        - PRODUCT_CATEGORY
        - PROCESS_DT
        - TRANSACTION_CODE
    DW_ANALYTICS.TRANSACTION_CODE:
        - INITIATION
        - TRANSACTION_CODE
*/
---CREDIT
INSERT INTO CINS_TMP_LST_11062023
SELECT 'CARD' PRODUCT, E.CUSTOMER_CDE 
FROM (
    SELECT CUSTOMER_CDE,
        'CARD_CREDIT_CT_TXN_6M' FTR_NM,
        COUNT(*) FTR_VAL,
        TO_DATE('11-06-2023','DD-MM-YY') RPT_DT,
        CURRENT_TIMESTAMP ADD_TSTP
    FROM CINS_TMP_CREDIT_CARD_TRANSACTION_11062023
    WHERE PROCESS_DT < TO_DATE('11-06-2023','DD-MM-YY')
        AND PROCESS_DT >= TO_DATE('11-06-2023','DD-MM-YY') - INTERVAL '6' MONTH
    GROUP BY CUSTOMER_CDE
) E
JOIN (
    SELECT CUSTOMER_CDE 
    FROM CINS_2M_PART 
    WHERE PRODUCT = 'CARD'
) F 
ON E.CUSTOMER_CDE = F.CUSTOMER_CDE
WHERE E.FTR_VAL > 0;


COMMIT;


---IB/MB
INSERT INTO CINS_TMP_LST_11062023
SELECT 'IBMB' PRODUCT, E.CUSTOMER_CDE 
FROM (
    SELECT CUSTOMER_CDE,
        'EB_MBIB_CT_TXN_6M' FTR_NM,
        COUNT(TXN_ID) FTR_VAL,
        TO_DATE('11-06-2023','DD-MM-YY') RPT_DT,
        CURRENT_TIMESTAMP ADD_TSTP
    FROM DW_ANALYTICS.DW_EB_TRANSACTION_FCT
    WHERE TXN_DT < TO_DATE('11-06-2023','DD-MM-YY')
        AND TXN_DT >= TO_DATE('11-06-2023','DD-MM-YY') - INTERVAL '6' MONTH
        AND TXN_STATUS = 'SUC'
        AND CUSTOMER_CDE IN (
            SELECT CUSTOMER_CDE 
            FROM CINS_TMP_CUSTOMER_11062023
        )
    GROUP BY CUSTOMER_CDE
) E 
JOIN (
    SELECT CUSTOMER_CDE 
    FROM CINS_2M_PART 
    WHERE PRODUCT = 'OTHER'
) F 
ON E.CUSTOMER_CDE = F.CUSTOMER_CDE
WHERE FTR_VAL > 0;


COMMIT;


---SACOMPAY
INSERT INTO CINS_TMP_LST_11062023
SELECT 'SACOMPAY' PRODUCT, E.CUSTOMER_CDE 
FROM (
    SELECT CUSTOMER_CDE,
        'EB_SACOMPAY_CT_TXN_6M' FTR_NM,
        COUNT(DISTINCT TXN_ID) FTR_VAL,
        TO_DATE('11-06-2023','DD-MM-YY') RPT_DT,
        CURRENT_TIMESTAMP ADD_TSTP
    FROM DW_ANALYTICS.DW_EWALL_TRANSACTION_FCT
    WHERE PROCESS_DT < TO_DATE('11-06-2023','DD-MM-YY') 
        AND PROCESS_DT >= TO_DATE('11-06-2023','DD-MM-YY') - INTERVAL '6' MONTH
        AND TXN_STATUS = 'S'
        AND CUSTOMER_CDE IN (
            SELECT CUSTOMER_CDE 
            FROM CINS_TMP_CUSTOMER_11062023
        )
    GROUP BY CUSTOMER_CDE
) E 
JOIN (
    SELECT CUSTOMER_CDE 
    FROM CINS_2M_PART 
    WHERE PRODUCT = 'OTHER'
) F 
ON E.CUSTOMER_CDE = F.CUSTOMER_CDE
WHERE FTR_VAL > 0;


COMMIT;


---CASA
INSERT INTO CINS_TMP_LST_11062023
SELECT 'CASA' PRODUCT, E.CUSTOMER_CDE 
FROM (
    SELECT CUSTOMER_ID CUSTOMER_CDE,
        'CASA_CT_TXN_6M' FTR_NM,
        COUNT(STMT_ENTRY_ID) FTR_VAL,
        TO_DATE('11-06-2023','DD-MM-YY') RPT_DT,
        CURRENT_TIMESTAMP ADD_TSTP
    FROM DW_ANALYTICS.DWA_STMT_EBANK TXN
    JOIN (
        SELECT TRANSACTION_CODE 
        FROM DW_ANALYTICS.TRANSACTION_CODE 
        WHERE INITIATION = 'CUSTOMER'
    ) TC
    ON TXN.TRANSACTION_CODE = TC.TRANSACTION_CODE
    WHERE PRODUCT_CATEGORY LIKE '10__'
        AND PROCESS_DT < TO_DATE('11-06-2023','DD-MM-YY')
        AND PROCESS_DT >= TO_DATE('11-06-2023','DD-MM-YY') - INTERVAL '6' MONTH
        AND CUSTOMER_ID IN (
            SELECT CUSTOMER_CDE 
            FROM CINS_TMP_CUSTOMER_11062023
        )
    GROUP BY CUSTOMER_ID
) E 
JOIN (
    SELECT CUSTOMER_CDE 
    FROM CINS_2M_PART 
    WHERE PRODUCT = 'OTHER'
) F 
ON E.CUSTOMER_CDE = F.CUSTOMER_CDE
WHERE FTR_VAL > 0;


COMMIT;