CREATE TABLE CINS_2M_PART AS (
    PRODUCT VARCHAR2(25 BYTE),
    CUSTOMER_CDE VARCHAR2(25 BYTE)
);


COMMIT;


CREATE TABLE CINS_TMP_LST_11062023 (
    PRODUCT VARCHAR(20), 
    CUSTOMER_CDE VARCHAR(20)
);


COMMIT;


/*
Table Name: CINS_TMP_CARD_DIM_11062023
Derived From: 
    DW_ANALYTICS.DWD_TOI_FCT: 
        - CUSTOMER_CDE
        - NII_DEPOSIT_MTH 
        - NII_LOAN_MTH 
        - NII_FEE_MTH 
        - NII_FX_MTH
        - PROCESS_DT
    DW_CUSTOMER_DIM:
        - ACTIVE
        - CUSTOMER_CDE
        - COMPANY_KEY
        - SUB_SECTOR_CDE
*/
INSERT INTO CINS_2M_PART
SELECT 'CARDS' PRODUCT, A.CUSTOMER_CDE 
FROM DW_ANALYTICS.DWA_CARD_TOI_FCT A
JOIN (
    SELECT CUSTOMER_CDE 
    FROM DW_ANALYTICS.DW_CUSTOMER_DIM
    WHERE ACTIVE = 1 
    AND COMPANY_KEY = 1 
    AND SUB_SECTOR_CDE IN ('1700', '1602')
) B 
ON A.CUSTOMER_CDE=B.CUSTOMER_CDE
WHERE TRUNC(A.PROCESS_DT) IN (
    '31-JAN-2022',
    '28-FEB-2022',
    '31-MAR-2022',
    '30-APR-2022',
    '31-MAY-2022',
    '30-JUN-2022',
    '31-JUL-2022',
    '31-AUG-2022',
    '30-SEP-2022',
    '31-OCT-2022',
    '30-NOV-2022',
    '31-DEC-2022'
)
GROUP BY A.CUSTOMER_CDE
HAVING SUM(A.NII_CARD_MTD)>=300000


COMMIT;


INSERT INTO CINS_2M_PART
SELECT 'OTHER' PRODUCT, A.CUSTOMER_CDE 
FROM (
    SELECT CUSTOMER_CDE, PROCESS_DT, (NII_DEPOSIT_MTH + NII_LOAN_MTH + NII_FEE_MTH + NII_FX_MTH) NII_CARD_MTD 
    FROM DW_ANALYTICS.DWD_TOI_FCT
) A
JOIN (
    SELECT CUSTOMER_CDE 
    FROM DW_ANALYTICS.DW_CUSTOMER_DIM
    WHERE ACTIVE = 1 
    AND COMPANY_KEY = 1 
    AND SUB_SECTOR_CDE IN ('1700', '1602')
) B 
ON A.CUSTOMER_CDE=B.CUSTOMER_CDE
WHERE TRUNC(A.PROCESS_DT) IN (
    '31-JAN-2022',
    '28-FEB-2022',
    '31-MAR-2022',
    '30-APR-2022',
    '31-MAY-2022',
    '30-JUN-2022',
    '31-JUL-2022',
    '31-AUG-2022',
    '30-SEP-2022',
    '31-OCT-2022',
    '30-NOV-2022',
    '31-DEC-2022'
)
GROUP BY A.CUSTOMER_CDE
HAVING SUM(A.NII_CARD_MTD)>=300000;


COMMIT;


/*
Table Name: CINS_TMP_CARD_DIM_11062023
Derived From: 
    CINS_TMP_CREDIT_CARD_TRANSACTION_11062023: 
        - CUSTOMER_CDE
        - PROCESS_DT
    CINS_2M_PART:
        - PRODUCT
        - CUSTOMER_CDE
    DW_ANALYTICS.DW_EB_TRANSACTION_FCT:
        - CUSTOMER_CDE
        - TXN_DT
        - TXN_STATUS
    DW_ANALYTICS.DW_EWALL_TRANSACTION_FCT:
        - CUSTOMER_CDE
        - PROCESS_DT
        - TXN_STATUS
    DW_ANALYTICS.DWA_STMT_EBANK:
        - CUSTOMER_ID
        - PRODUCT_CATEGORY
        - PROCESS_DT
        - TRANSACTION_CODE
    DW_ANALYTICS.TRANSACTION_CODE:
        - INITIATION
        - TRANSACTION_CODE
*/
---CREDIT
INSERT INTO CINS_TMP_LST_11062023
SELECT 'CARD' PRODUCT, E.CUSTOMER_CDE 
FROM (
    SELECT CUSTOMER_CDE,
        'CARD_CREDIT_CT_TXN_6M' FTR_NM,
        COUNT(*) FTR_VAL,
        TO_DATE('11-06-2023','DD-MM-YY') RPT_DT,
        CURRENT_TIMESTAMP ADD_TSTP
    FROM CINS_TMP_CREDIT_CARD_TRANSACTION_11062023
    WHERE PROCESS_DT < TO_DATE('11-06-2023','DD-MM-YY')
        AND PROCESS_DT >= TO_DATE('11-06-2023','DD-MM-YY') - INTERVAL '6' MONTH
    GROUP BY CUSTOMER_CDE
) E
JOIN (
    SELECT CUSTOMER_CDE 
    FROM CINS_2M_PART 
    WHERE PRODUCT = 'CARD'
) F 
ON E.CUSTOMER_CDE = F.CUSTOMER_CDE
WHERE E.FTR_VAL > 0;


COMMIT;


---IB/MB
INSERT INTO CINS_TMP_LST_11062023
SELECT 'IBMB' PRODUCT, E.CUSTOMER_CDE 
FROM (
    SELECT CUSTOMER_CDE,
        'EB_MBIB_CT_TXN_6M' FTR_NM,
        COUNT(TXN_ID) FTR_VAL,
        TO_DATE('11-06-2023','DD-MM-YY') RPT_DT,
        CURRENT_TIMESTAMP ADD_TSTP
    FROM DW_ANALYTICS.DW_EB_TRANSACTION_FCT
    WHERE TXN_DT < TO_DATE('11-06-2023','DD-MM-YY')
        AND TXN_DT >= TO_DATE('11-06-2023','DD-MM-YY') - INTERVAL '6' MONTH
        AND TXN_STATUS = 'SUC'
        AND CUSTOMER_CDE IN (
            SELECT CUSTOMER_CDE 
            FROM CINS_TMP_CUSTOMER_11062023
        )
    GROUP BY CUSTOMER_CDE
) E 
JOIN (
    SELECT CUSTOMER_CDE 
    FROM CINS_2M_PART 
    WHERE PRODUCT = 'OTHER'
) F 
ON E.CUSTOMER_CDE = F.CUSTOMER_CDE
WHERE FTR_VAL > 0;


COMMIT;


---SACOMPAY
INSERT INTO CINS_TMP_LST_11062023
SELECT 'SACOMPAY' PRODUCT, E.CUSTOMER_CDE 
FROM (
    SELECT CUSTOMER_CDE,
        'EB_SACOMPAY_CT_TXN_6M' FTR_NM,
        COUNT(DISTINCT TXN_ID) FTR_VAL,
        TO_DATE('11-06-2023','DD-MM-YY') RPT_DT,
        CURRENT_TIMESTAMP ADD_TSTP
    FROM DW_ANALYTICS.DW_EWALL_TRANSACTION_FCT
    WHERE PROCESS_DT < TO_DATE('11-06-2023','DD-MM-YY') 
        AND PROCESS_DT >= TO_DATE('11-06-2023','DD-MM-YY') - INTERVAL '6' MONTH
        AND TXN_STATUS = 'S'
        AND CUSTOMER_CDE IN (
            SELECT CUSTOMER_CDE 
            FROM CINS_TMP_CUSTOMER_11062023
        )
    GROUP BY CUSTOMER_CDE
) E 
JOIN (
    SELECT CUSTOMER_CDE 
    FROM CINS_2M_PART 
    WHERE PRODUCT = 'OTHER'
) F 
ON E.CUSTOMER_CDE = F.CUSTOMER_CDE
WHERE FTR_VAL > 0;


COMMIT;


---CASA
INSERT INTO CINS_TMP_LST_11062023
SELECT 'CASA' PRODUCT, E.CUSTOMER_CDE 
FROM (
    SELECT CUSTOMER_ID CUSTOMER_CDE,
        'CASA_CT_TXN_6M' FTR_NM,
        COUNT(STMT_ENTRY_ID) FTR_VAL,
        TO_DATE('11-06-2023','DD-MM-YY') RPT_DT,
        CURRENT_TIMESTAMP ADD_TSTP
    FROM DW_ANALYTICS.DWA_STMT_EBANK TXN
    JOIN (
        SELECT TRANSACTION_CODE 
        FROM DW_ANALYTICS.TRANSACTION_CODE 
        WHERE INITIATION = 'CUSTOMER'
    ) TC
    ON TXN.TRANSACTION_CODE = TC.TRANSACTION_CODE
    WHERE PRODUCT_CATEGORY LIKE '10__'
        AND PROCESS_DT < TO_DATE('11-06-2023','DD-MM-YY')
        AND PROCESS_DT >= TO_DATE('11-06-2023','DD-MM-YY') - INTERVAL '6' MONTH
        AND CUSTOMER_ID IN (
            SELECT CUSTOMER_CDE 
            FROM CINS_TMP_CUSTOMER_11062023
        )
    GROUP BY CUSTOMER_ID
) E 
JOIN (
    SELECT CUSTOMER_CDE 
    FROM CINS_2M_PART 
    WHERE PRODUCT = 'OTHER'
) F 
ON E.CUSTOMER_CDE = F.CUSTOMER_CDE
WHERE FTR_VAL > 0;


COMMIT;


/*
Feature Name: CASA_AVG_BAL_1M
Derived From: 
  DW_ANALYTICS.DW_DEPOSIT_FCT: 
    - CATEGORY_CDE
    - CUSTOMER_CDE
    - ACTUAL_BAL_LCL
    - PROCESS_DT
  CINS_TMP_CUSTOMER_11062023:
    - CUSTOMER_CDE 
Tags: 
  - CASA
TW: 1M
*/
INSERT INTO CINS_FEATURE_STORE_V2
SELECT CUSTOMER_CDE,
  'CASA_AVG_BAL_1M' AS FTR_NM,
  AVG(ACTUAL_BAL_LCL) AS FTR_VAL,
  TO_DATE('11-06-2023', 'DD-MM-YY') AS RPT_DT,
  CURRENT_TIMESTAMP ADD_TSTP
FROM DW_ANALYTICS.DW_DEPOSIT_FCT
WHERE CATEGORY_CDE LIKE '10__'
  AND CUSTOMER_CDE IN (SELECT CUSTOMER_CDE FROM CINS_TMP_CUSTOMER_11062023)
  AND ADD_MONTHS(TO_DATE('11-06-2023', 'DD-MM-YY'), -1) <= PROCESS_DT
  AND PROCESS_DT < TO_DATE('11-06-2023', 'DD-MM-YY')
GROUP BY CUSTOMER_CDE;


COMMIT;


/*
Feature Name: CASA_CT_ACCT_ACTIVE
Derived From: 
  DW_ANALYTICS.DW_ACCOUNT_MASTER_DIM:  
    - ACCT_ID
    - ACTIVE
    - CUSTOMER_CDE
  DW_ANALYTICS.DWA_STMT_EBANK: 
    - TRANSACTION_CODE
    - CUSTOMER_ID
    - PRODUCT_CATEGORY
    - ACCOUNT_NUMBER
    - PROCESS_DT
  DW_ANALYTICS.TRANSACTION_CODE: 
    - TRANSACTION_CODE
    - INITIATION
  CINS_TMP_CUSTOMER_11062023:
    - CUSTOMER_CDE
Tags: 
  - CASA
TW: 12M
*/
INSERT INTO CINS_FEATURE_STORE_V2
SELECT CUSTOMER_CDE,
       'CASA_CT_ACCT_ACTIVE' FTR_NM,
        COUNT(DISTINCT ACCT_ID) FTR_VAL,
        TO_DATE('11-06-2023', 'DD-MM-YY') AS RPT_DT,
        CURRENT_TIMESTAMP ADD_TSTP
FROM DW_ANALYTICS.DW_ACCOUNT_MASTER_DIM DIM
WHERE ACTIVE = 1
  AND EXISTS
    (SELECT CUSTOMER_ID
     FROM DW_ANALYTICS.DWA_STMT_EBANK FCT
     JOIN
       (SELECT TRANSACTION_CODE
        FROM DW_ANALYTICS.TRANSACTION_CODE
        WHERE INITIATION = 'CUSTOMER') TC ON FCT.TRANSACTION_CODE = TC.TRANSACTION_CODE
     WHERE DIM.CUSTOMER_CDE = FCT.CUSTOMER_ID
       AND PRODUCT_CATEGORY LIKE '10__'
       AND CUSTOMER_ID IN
         (SELECT CUSTOMER_CDE
          FROM CINS_TMP_CUSTOMER_11062023)
       AND DIM.ACCT_ID = FCT.ACCOUNT_NUMBER
       AND PROCESS_DT < TO_DATE('11-06-2023', 'DD-MM-YY')
       AND PROCESS_DT >= ADD_MONTHS(TO_DATE('11-06-2023', 'DD-MM-YY'), -12) )
GROUP BY CUSTOMER_CDE;


COMMIT;


/*
Feature Name: CASA_CT_TXN_1M
Derived From: 
  DW_ANALYTICS.DWA_STMT_EBANK: 
    - STMT_ENTRY_ID
    - CUSTOMER_ID
    - PRODUCT_CATEGORY
    - PROCESS_DT
    - TRANSACTION_CODE
  DW_ANALYTICS.TRANSACTION_CODE: 
    - TRANSACTION_CODE
    - INITIATION
  CINS_TMP_CUSTOMER_11062023:
    - CUSTOMER_CDE
Tags: 
  - CASA
TW: 1M
*/
INSERT INTO CINS_FEATURE_STORE_V2
SELECT CUSTOMER_ID AS CUSTOMER_CDE,
    'CASA_CT_TXN_1M' AS FTR_NM,
    COUNT(STMT_ENTRY_ID) AS FTR_VAL,
    TO_DATE('11-06-2023', 'DD-MM-YY') AS RPT_DT,
    CURRENT_TIMESTAMP AS ADD_TSTP
FROM DW_ANALYTICS.DWA_STMT_EBANK TXN
JOIN
  (SELECT TRANSACTION_CODE
   FROM DW_ANALYTICS.TRANSACTION_CODE
   WHERE INITIATION = 'CUSTOMER') TC ON TXN.TRANSACTION_CODE = TC.TRANSACTION_CODE
WHERE PRODUCT_CATEGORY LIKE '10__'
  AND PROCESS_DT < TO_DATE('11-06-2023', 'DD-MM-YY')
  AND PROCESS_DT >= ADD_MONTHS(TO_DATE('11-06-2023', 'DD-MM-YY'), -1)
  AND CUSTOMER_ID IN
    (SELECT CUSTOMER_CDE
     FROM CINS_TMP_CUSTOMER_11062023)
GROUP BY CUSTOMER_ID;


COMMIT;


/* 
Feature Name: CASA_DAY_SINCE_LTST_TXN
Derived From: 
  DW_ANALYTICS.DWA_STMT_EBANK: 
    - CUSTOMER_ID
    - PROCESS_DT
    - PRODUCT_CATEGORY
    - TRANSACTION_CODE
  DW_ANALYTICS.TRANSACTION_CODE: 
    - TRANSACTION_CODE
  CINS_TMP_CUSTOMER_11062023:
    - CUSTOMER_CDE
Tags: 
  - CASA
TW: 36M
*/ 
INSERT INTO CINS_FEATURE_STORE_V2
SELECT CUSTOMER_ID AS CUSTOMER_CDE,
    'CASA_DAY_SINCE_LTST_TXN' FTR_NM,
    TO_DATE('11-06-2023', 'DD-MM-YY') - NVL(MAX(PROCESS_DT), ADD_MONTHS(TO_DATE('11-06-2023', 'DD-MM-YY'), -36)) FTR_VAL,
    TO_DATE('11-06-2023', 'DD-MM-YY') AS RPT_DT,
    CURRENT_TIMESTAMP ADD_TSTP
FROM DW_ANALYTICS.DWA_STMT_EBANK TXN
JOIN
  (SELECT TRANSACTION_CODE
   FROM DW_ANALYTICS.TRANSACTION_CODE
   WHERE INITIATION = 'CUSTOMER') TC ON TXN.TRANSACTION_CODE = TC.TRANSACTION_CODE
WHERE PRODUCT_CATEGORY LIKE '10__'
  AND PROCESS_DT < TO_DATE('11-06-2023', 'DD-MM-YY')
  AND PROCESS_DT >= ADD_MONTHS(TO_DATE('11-06-2023', 'DD-MM-YY'), -36)
  AND CUSTOMER_ID IN
    (SELECT CUSTOMER_CDE
     FROM CINS_TMP_CUSTOMER_11062023)
GROUP BY CUSTOMER_ID;


COMMIT;


/*
Feature Name: CASA_MAX_BAL_1M
Derived From: 
  DW_ANALYTICS.DW_DEPOSIT_FCT:  
    - ACTUAL_BAL_LCL
    - CATEGORY_CDE
    - CUSTOMER_CDE
    - PROCESS_DT
  CINS_TMP_CUSTOMER_11062023:
    - CUSTOMER_CDE
Tags: 
  - CASA
TW: 1M
*/
INSERT INTO CINS_FEATURE_STORE_V2
SELECT CUSTOMER_CDE,
    'CASA_MAX_BAL_1M' AS FTR_NM,
    MAX(ACTUAL_BAL_LCL) AS FTR_VAL,
    TO_DATE('11-06-2023', 'DD-MM-YY') AS RPT_DT,
    CURRENT_TIMESTAMP ADD_TSTP
FROM DW_ANALYTICS.DW_DEPOSIT_FCT
WHERE CATEGORY_CDE LIKE '10__'
  AND CUSTOMER_CDE IN
    (SELECT CUSTOMER_CDE
     FROM CINS_TMP_CUSTOMER_11062023)
  AND ADD_MONTHS(TO_DATE('11-06-2023', 'DD-MM-YY'), -1) <= PROCESS_DT
  AND PROCESS_DT < TO_DATE('11-06-2023', 'DD-MM-YY')
GROUP BY CUSTOMER_CDE;


COMMIT;


/*
Feature Name: CASA_MIN_BAL_1M
Derived From: 
  DW_ANALYTICS.DW_DEPOSIT_FCT: 
    - ACTUAL_BAL_LCL
    - CATEGORY_CDE
    - CUSTOMER_CDE
    - PROCESS_DT
  CINS_TMP_CUSTOMER_11062023:
    - CUSTOMER_CDE
Tags: 
  - CASA
TW: 1M
*/
INSERT INTO CINS_FEATURE_STORE_V2
SELECT CUSTOMER_CDE,
       'CASA_MIN_BAL_1M' AS FTR_NM,
       MIN(ACTUAL_BAL_LCL) AS FTR_VAL,
       TO_DATE('11-06-2023', 'DD-MM-YY') AS RPT_DT,
       CURRENT_TIMESTAMP ADD_TSTP
FROM DW_ANALYTICS.DW_DEPOSIT_FCT
WHERE CATEGORY_CDE LIKE '10__'
  AND CUSTOMER_CDE IN
    (SELECT CUSTOMER_CDE
     FROM CINS_TMP_CUSTOMER_11062023)
  AND ADD_MONTHS(TO_DATE('11-06-2023', 'DD-MM-YY'), -1) <= PROCESS_DT
  AND PROCESS_DT < TO_DATE('11-06-2023', 'DD-MM-YY')
GROUP BY CUSTOMER_CDE;


COMMIT;


/*
Feature Name: CASA_SUM_TXN_AMT_1M
Derived From: 
  DW_ANALYTICS.DWA_STMT_EBANK: 
    - AMT_LCY
    - PRODUCT_CATEGORY
    - PROCESS_DT
    - CUSTOMER_CDE
    - TRANSACTION_CODE
  DW_ANALYTICS.TRANSACTION_CODE: 
    - TRANSACTION_CODE
    - INITIATION
  CINS_TMP_CUSTOMER_11062023:
    - CUSTOMER_CDE
Tags: 
  - CASA
TW: 1M
*/
INSERT INTO CINS_FEATURE_STORE_V2
SELECT CUSTOMER_ID AS CUSTOMER_CDE,
       'CASA_SUM_TXN_AMT_1M' FTR_NM,
        NVL(SUM(ABS(AMT_LCY)), 0) FTR_VAL,
        TO_DATE('11-06-2023', 'DD-MM-YY') AS RPT_DT,
        CURRENT_TIMESTAMP ADD_TSTP
FROM DW_ANALYTICS.DWA_STMT_EBANK TXN
JOIN
  (SELECT TRANSACTION_CODE
   FROM DW_ANALYTICS.TRANSACTION_CODE
   WHERE INITIATION = 'CUSTOMER') TC ON TXN.TRANSACTION_CODE = TC.TRANSACTION_CODE
WHERE PRODUCT_CATEGORY LIKE '10__'
  AND PROCESS_DT < TO_DATE('11-06-2023', 'DD-MM-YY')
  AND PROCESS_DT >= ADD_MONTHS(TO_DATE('11-06-2023', 'DD-MM-YY'), -1)
  AND CUSTOMER_ID IN
    (SELECT CUSTOMER_CDE
     FROM CINS_TMP_CUSTOMER_11062023)
GROUP BY CUSTOMER_ID;