/*
Feature Name: CASA_ACCT_ACTIVE_CT_12M
Derived From: 
  DW_ANALYTICS.DW_ACCOUNT_MASTER_DIM:  
    - ACCT_ID
    - ACTIVE
    - CUSTOMER_CDE
  DW_ANALYTICS.DWA_STMT_EBANK: 
    - TRANSACTION_CODE
    - CUSTOMER_ID
    - PRODUCT_CATEGORY
    - ACCOUNT_NUMBER
    - PROCESS_DT
  DW_ANALYTICS.TRANSACTION_CODE: 
    - TRANSACTION_CODE
    - INITIATION
  CINS_TMP_CUSTOMER_11062023:
    - CUSTOMER_CDE
Tags: 
  - CASA
  - BEHAVIORAL
TW: 12M
Desc: 