/*
Feature Name: CASA_ACCT_COMBO_CT_36M
Derived From: 
  DWPROD.DW_ACCOUNT_MASTER_DIM:  
    - ACCT_ID
    - ACTIVE
    - CUSTOMER_CDE
  DWPROD.DWA_STMT_EBANK: 
    - TRANSACTION_CODE
    - CUSTOMER_ID
    - PRODUCT_CATEGORY
    - ACCOUNT_NUMBER
    - PROCESS_DT
  DWPROD.TRANSACTION_CODE: 
    - TRANSACTION_CODE
    - INITIATION
  DWPROD.DWL_PRODUCT_MASTER_DIM:
    - CATEGORY_CDE
    - PRODUCT_NM_LVL_2
    - PRODUCT_NM_LVL_3
  CINS_TMP_CUSTOMER_11062023:
    - CUSTOMER_CDE
Tags: 
  - CASA
  - BEHAVIORAL
TW: 36M
*/
INSERT INTO CINS_FEATURE_STORE_V2
SELECT
  DIM.CUSTOMER_CDE,
  'CASA_ACCT_COMBO_CT_36M' FTR_NM,
  COUNT(DISTINCT DIM.ACCT_ID) AS FTR_VAL,
  TO_DATE('11-06-2023', 'DD-MM-YY') AS RPT_DT,
  CURRENT_TIMESTAMP AS ADD_TSTP
FROM DWPROD.DW_ACCOUNT_MASTER_DIM DIM
JOIN DWPROD.DWA_STMT_EBANK FCT ON DIM.CUSTOMER_CDE = FCT.CUSTOMER_ID
JOIN DWPROD.TRANSACTION_CODE TC ON FCT.TRANSACTION_CODE = TC.TRANSACTION_CODE
JOIN DWPROD.DWL_PRODUCT_MASTER_DIM PM ON FCT.PRODUCT_CATEGORY = PM.CATEGORY_CDE
WHERE DIM.ACTIVE = 1
  AND DIM.ACCT_ID = FCT.ACCOUNT_NUMBER
  AND TC.INITIATION = 'CUSTOMER'
  AND FCT.PRODUCT_CATEGORY LIKE '10__'
  AND FCT.PROCESS_DT < TO_DATE('11-06-2023', 'DD-MM-YY')
  AND (UPPER(PM.PRODUCT_NM_LVL_2) LIKE '%COMBO%' OR UPPER(PM.PRODUCT_NM_LVL_3) LIKE '%COMBO%')
  AND FCT.PROCESS_DT >= ADD_MONTHS(TO_DATE('11-06-2023', 'DD-MM-YY'), -36)
GROUP BY DIM.CUSTOMER_CDE;


COMMIT;


/*
Feature Name: CASA_ACCT_PAYROLL_CT_36M
Derived From: 
  DWPROD.DW_ACCOUNT_MASTER_DIM:  
    - ACCT_ID
    - ACTIVE
    - CUSTOMER_CDE
  DWPROD.DWA_STMT_EBANK: 
    - TRANSACTION_CODE
    - CUSTOMER_ID
    - PRODUCT_CATEGORY
    - ACCOUNT_NUMBER
    - PROCESS_DT
  DWPROD.TRANSACTION_CODE: 
    - TRANSACTION_CODE
    - INITIATION
  DWPROD.DWL_PRODUCT_MASTER_DIM:
    - CATEGORY_CDE
    - PRODUCT_NM_LVL_2
    - PRODUCT_NM_LVL_3
  CINS_TMP_CUSTOMER_11062023:
    - CUSTOMER_CDE
Tags: 
  - CASA
  - BEHAVIORAL
TW: 36M
*/
INSERT INTO CINS_FEATURE_STORE_V2
SELECT
  DIM.CUSTOMER_CDE,
  'CASA_ACCT_PAYROLL_CT_36M' FTR_NM,
  COUNT(DISTINCT DIM.ACCT_ID) AS FTR_VAL,
  TO_DATE('11-06-2023', 'DD-MM-YY') AS RPT_DT,
  CURRENT_TIMESTAMP AS ADD_TSTP
FROM DWPROD.DW_ACCOUNT_MASTER_DIM DIM
JOIN DWPROD.DWA_STMT_EBANK FCT ON DIM.CUSTOMER_CDE = FCT.CUSTOMER_ID
JOIN DWPROD.TRANSACTION_CODE TC ON FCT.TRANSACTION_CODE = TC.TRANSACTION_CODE
JOIN DWPROD.DWL_PRODUCT_MASTER_DIM PM ON FCT.PRODUCT_CATEGORY = PM.CATEGORY_CDE
WHERE DIM.ACTIVE = 1
  AND DIM.ACCT_ID = FCT.ACCOUNT_NUMBER
  AND TC.INITIATION = 'CUSTOMER'
  AND FCT.PRODUCT_CATEGORY LIKE '10__'
  AND FCT.PROCESS_DT < TO_DATE('11-06-2023', 'DD-MM-YY')
  AND (UPPER(PM.PRODUCT_NM_LVL_2) LIKE '%PAYROLL%' OR UPPER(PM.PRODUCT_NM_LVL_3) LIKE '%PAYROLL%')
  AND FCT.PROCESS_DT >= ADD_MONTHS(TO_DATE('11-06-2023', 'DD-MM-YY'), -36)
GROUP BY DIM.CUSTOMER_CDE;


COMMIT;