/*
Feature Name: SACOMBANK_PAY_CROSS_SELL_LABEL1
Derived From: DW_EWALL_USER_DIM, CINS_TMP_CUSTOMER_{RPT_DT_TBL}
*/
INSERT INTO {TBL_NM} 
WITH A AS
  (SELECT CUSTOMER_CDE,
          EWALL_ID,
          FIRST_SIGNED_ON
   FROM
     (SELECT CUSTOMER_CDE,
             EWALL_ID,
             FIRST_SIGNED_ON,
             ROW_NUMBER() OVER(PARTITION BY CUSTOMER_CDE, EWALL_ID
                               ORDER BY REC_UPDATE_DT DESC) RN
      FROM DW_ANALYTICS.DW_EWALL_USER_DIM
      WHERE CUSTOMER_CDE IN
          (SELECT CUSTOMER_CDE
           FROM CINS_TMP_CUSTOMER_{RPT_DT_TBL})
        AND USER_STATUS = 'A' )
   WHERE RN = 1 )
SELECT CUSTOMER_CDE,
       'SACOMBANK_PAY_CROSS_SELL_LABEL1' AS FTR_NM,
       TO_CHAR(FIRST_SIGNED_ON) AS FTR_VAL,
       TO_DATE('{RPT_DT}', 'DD-MM-YY') AS RPT_DT,
       CURRENT_TIMESTAMP AS ADD_TSTP
FROM
  (SELECT CUSTOMER_CDE,
          EWALL_ID,
          FIRST_SIGNED_ON,
          ROW_NUMBER() OVER(PARTITION BY CUSTOMER_CDE
                            ORDER BY FIRST_SIGNED_ON DESC) RN
   FROM A
   WHERE FIRST_SIGNED_ON < TO_DATE('{RPT_DT}', 'DD-MM-YY') )
WHERE RN = 1