INSERT INTO CINS_FEATURE_STORE_REACTIVATED_01052023
WITH
T0 AS (
    SELECT * FROM CINS_REACTIVATED_CASA_CUSTOMER_01052023),
T1 AS (
    SELECT * FROM DW_ANALYTICS.DW_LOAN_FCT),
T2 AS (
    SELECT * FROM DW_ANALYTICS.DW_SBVCODE_DIM)
SELECT 
T0.CUSTOMER_CDE AS CUSTOMER_CDE, 
'LOAN_SUM_LATEST' AS FTR_NM,
SUM(OS_AMT_LCL) AS FTR_VAL,
TO_DATE('01-05-2023', 'DD-MM-YY') AS RPT_DT,
CURRENT_TIMESTAMP AS ADD_TSTP
FROM T0
LEFT JOIN T1 ON T0.CUSTOMER_CDE = T1.CUSTOMER_CDE
INNER JOIN T2 ON T2.SBVCODE_LVL_3 = T1.SBVCODE_LVL_3
WHERE T2.APPLICATION = 'LN' AND T1.PROCESS_DT = TO_DATE('30-04-2023', 'DD-MM-YY')
AND T0.CUSTOMER_CDE IS NOT NULL
GROUP BY T0.CUSTOMER_CDE;