/*
Feature Name: REACTIVATED
Derived From: CINS_TMP_CUSTOMER_STATUS_{RPT_DT_TBL}
*/
INSERT INTO {TBL_NM}
SELECT CUSTOMER_CDE,
       'REACTIVATED' FTR_NM,
       1 FTR_VAL,
       TO_DATE('{RPT_DT}', 'DD-MM-YY') AS RPT_DT,
       CURRENT_TIMESTAMP ADD_TSTP
FROM CINS_TMP_CUSTOMER_STATUS_{RPT_DT_TBL}
WHERE CUST_STT = 2
  AND CUST_STT_CHG = 1
  AND RPT_DT = TO_DATE('{RPT_DT}', 'DD-MM-YY');

/*
Feature Name: EB_MBIB_INACTIVE
Derived From: DW_EB_TRANSACTION_FCT, DW_CUSTOMER_DIM
*/
INSERT INTO {TBL_NM}
SELECT CUSTOMER_CDE,
       'EB_MBIB_INACTIVE' FTR_NM,
                          1 FTR_VAL,
                          TO_DATE('{RPT_DT}', 'DD-MM-YY') AS RPT_DT,
                          CURRENT_TIMESTAMP ADD_TSTP
FROM DW_ANALYTICS.DW_CUSTOMER_DIM
WHERE ACTIVE = 1
  AND COMPANY_KEY = 1
  AND SUB_SECTOR_CDE IN ('1700',
                         '1602')
  AND CUSTOMER_CDE IN
    (SELECT CUSTOMER_CDE
     FROM DW_ANALYTICS.DW_EB_TRANSACTION_FCT
     WHERE TXN_STATUS = 'SUC'
       AND TXN_DT < ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -12)
       AND TXN_DT >= ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -36)
       AND CUSTOMER_CDE IS NOT NULL)
  AND CUSTOMER_CDE NOT IN
    (SELECT CUSTOMER_CDE
     FROM DW_ANALYTICS.DW_EB_TRANSACTION_FCT
     WHERE TXN_STATUS = 'SUC'
       AND TXN_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')
       AND TXN_DT >= ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -12)
       AND CUSTOMER_CDE IS NOT NULL);


/*
Feature Name: CASA_INACTIVE
Derived From: DWA_STMT_EBANK, TRANSACTION_CODE, DW_CUSTOMER_DIM
*/
INSERT INTO {TBL_NM}
SELECT CUSTOMER_CDE,
       'CASA_INACTIVE' FTR_NM,
                       1 FTR_VAL,
                       TO_DATE('{RPT_DT}', 'DD-MM-YY') AS RPT_DT,
                       CURRENT_TIMESTAMP ADD_TSTP
FROM DW_ANALYTICS.DW_CUSTOMER_DIM
WHERE ACTIVE = 1
  AND COMPANY_KEY = 1
  AND SUB_SECTOR_CDE IN ('1700',
                         '1602')
  AND CUS_OPEN_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')
  AND CUSTOMER_CDE NOT IN
    (SELECT CUSTOMER_ID
     FROM DW_ANALYTICS.DWA_STMT_EBANK TXN
     JOIN
       (SELECT TRANSACTION_CODE
        FROM DW_ANALYTICS.TRANSACTION_CODE
        WHERE INITIATION = 'CUSTOMER') TC ON TXN.TRANSACTION_CODE = TC.TRANSACTION_CODE
     WHERE PRODUCT_CATEGORY LIKE '10__'
       AND PROCESS_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')
       AND PROCESS_DT >= ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -12))
  AND CUSTOMER_CDE IN
    (SELECT CUSTOMER_ID
     FROM DW_ANALYTICS.DWA_STMT_EBANK TXN
     JOIN
       (SELECT TRANSACTION_CODE
        FROM DW_ANALYTICS.TRANSACTION_CODE
        WHERE INITIATION = 'CUSTOMER') TC ON TXN.TRANSACTION_CODE = TC.TRANSACTION_CODE
     WHERE PRODUCT_CATEGORY LIKE '10__'
       AND PROCESS_DT < ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -12)
       AND PROCESS_DT >= ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -36));

/*
Feature Name: CASA_INACTIVE
Derived From: DWA_STMT_EBANK, TRANSACTION_CODE, DW_CUSTOMER_DIM, STG_ACCT
*/
INSERT INTO {TBL_NM}
SELECT CUSTOMER_CDE,
       'CASA_INACTIVE' FTR_NM,
                       1 FTR_VAL,
                       TO_DATE('{RPT_DT}', 'DD-MM-YY') AS RPT_DT,
                       CURRENT_TIMESTAMP ADD_TSTP
FROM DW_ANALYTICS.DW_CUSTOMER_DIM
WHERE ACTIVE = 1
  AND COMPANY_KEY = 1
  AND SUB_SECTOR_CDE IN ('1700',
                         '1602')
  AND CUS_OPEN_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')
  AND CUSTOMER_CDE IN
    (SELECT CAST(AC_CUST_ID AS VARCHAR2(9)) CUSTOMER_CDE
     FROM DW_ANALYTICS.STG_ACCT
     WHERE AC_CATEGORY LIKE '10__'
       AND NVL(AC_OPENING_DATE, AC_VALUE_DATE) < TO_DATE('{RPT_DT}', 'DD-MM-YY')
       AND NVL(AC_OPENING_DATE, AC_VALUE_DATE) >= ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -36)
     UNION SELECT CUSTOMER_CDE
     FROM {TBL_NM}
     WHERE CAST(FTR_VAL AS NUMBER(38, 2)) > 0
       AND FTR_NM = 'CASA_SUM_BAL_NOW'
       AND RPT_DT = TO_CHAR(TO_DATE('{RPT_DT}', 'DD-MM-YY'), 'DD-MM-YYYY') )
  AND CUSTOMER_CDE NOT IN
    (SELECT CUSTOMER_ID
     FROM DW_ANALYTICS.DWA_STMT_EBANK TXN
     JOIN
       (SELECT TRANSACTION_CODE
        FROM DW_ANALYTICS.TRANSACTION_CODE
        WHERE INITIATION = 'CUSTOMER') TC ON TXN.TRANSACTION_CODE = TC.TRANSACTION_CODE
     WHERE PRODUCT_CATEGORY LIKE '10__'
       AND PROCESS_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')
       AND PROCESS_DT >= ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -36) );

/*
Feature Name: CARD_CREDIT_INACTIVE
Derived From: DW_CUSTOMER_DIM, DW_CARD_TRANSACTION_FCT, DW_CARD_MASTER_DIM
*/
INSERT INTO {TBL_NM}
SELECT CUSTOMER_CDE,
       'CARD_CREDIT_INACTIVE' FTR_NM,
                              1 FTR_VAL,
                              TO_DATE('{RPT_DT}', 'DD-MM-YY') AS RPT_DT,
                              CURRENT_TIMESTAMP ADD_TSTP
FROM DW_ANALYTICS.DW_CUSTOMER_DIM
WHERE ACTIVE = 1
  AND COMPANY_KEY = 1
  AND SUB_SECTOR_CDE IN ('1700',
                         '1602')
  AND CUSTOMER_CDE IN
    (SELECT CUSTOMER_CDE
     FROM DW_ANALYTICS.DW_CARD_MASTER_DIM
     WHERE CARD_CDE LIKE '3%'
       AND STATUS_CDE = ' '
       AND ACTIVATION_DT < ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -3)
       AND TO_CHAR(ACTIVATION_DT, 'yyyy') > 1900)
  AND CUSTOMER_CDE NOT IN
    (SELECT CUSTOMER_CDE
     FROM DW_ANALYTICS.DW_CARD_TRANSACTION_FCT
     WHERE CARD_CDE LIKE '3%'
       AND TRAN_STATUS = 'S'
       AND POST_DT IS NOT NULL
       AND MCC_CDE NOT IN (0,
                           4829)
       AND MCC_CDE IS NOT NULL
       AND PROCESS_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')
       AND PROCESS_DT >= ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -3));

/*
Feature Name: EB_SACOMPAY_INACTIVE
Derived From: DW_EWALL_TRANSACTION_FCT, DW_CUSTOMER_DIM
*/
INSERT INTO {TBL_NM}
SELECT CUSTOMER_CDE,
       'EB_SACOMPAY_INACTIVE' FTR_NM,
                              1 FTR_VAL,
                              TO_DATE('{RPT_DT}', 'DD-MM-YY') AS RPT_DT,
                              CURRENT_TIMESTAMP ADD_TSTP
FROM DW_ANALYTICS.DW_CUSTOMER_DIM
WHERE ACTIVE = 1
  AND COMPANY_KEY = 1
  AND SUB_SECTOR_CDE IN ('1700',
                         '1602')
  AND CUSTOMER_CDE IN
    (SELECT CUSTOMER_CDE
     FROM DW_ANALYTICS.DW_EWALL_TRANSACTION_FCT
     WHERE TXN_STATUS = 'S'
       AND TXN_DT < ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -12)
       AND TXN_DT >= ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -36)
       AND CUSTOMER_CDE IS NOT NULL)
  AND CUSTOMER_CDE NOT IN
    (SELECT CUSTOMER_CDE
     FROM DW_ANALYTICS.DW_EWALL_TRANSACTION_FCT
     WHERE TXN_STATUS = 'S'
       AND TXN_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')
       AND TXN_DT >= ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -12)
       AND CUSTOMER_CDE IS NOT NULL);