CREATE TABLE CINS_TMP_CREDIT_CARD_TRANSACTION_07082023 (
    CUSTOMER_CDE VARCHAR2(25 BYTE),
    PROCESS_DT DATE,
    APPROVAL_CDE VARCHAR2(25 BYTE),
    RETRVL_REFNO VARCHAR2(25 BYTE),
    AMT_BILL NUMBER,
    ACQ_CNTRY_CDE VARCHAR2(25 BYTE),
    MERCHANT_CDE VARCHAR2(25 BYTE),
    TXN_CURR_CDE VARCHAR2(25 BYTE),
    BILL_CURR_CDE VARCHAR2(25 BYTE),
    PRODUCT_CDE VARCHAR2(25 BYTE),
    TXN_OL_CDE VARCHAR2(25 BYTE),
    MCC_CDE NUMBER,
    TXN_OM_CDE VARCHAR2(25 BYTE),
    AMT_FEE NUMBER
)