/*
Feature Name: EB_MBIB_DAY_SINCE_ACTIVE
Derived From: DW_EB_USER, CINS_TMP_CUSTOMER_{RPT_DT_TBL}
*/
INSERT INTO {TBL_NM}
SELECT CUSTOMER_CDE,
       'EB_MBIB_DAY_SINCE_ACTIVE' FTR_NM,
       TO_DATE('{RPT_DT}', 'DD-MM-YY') - ACTIVATE_DATE FTR_VAL,
       TO_DATE('{RPT_DT}', 'DD-MM-YY') AS RPT_DT,
       CURRENT_TIMESTAMP ADD_TSTP
FROM
  (SELECT CUSTOMER_CDE,
          min(ACTIVATE_DT) ACTIVATE_DATE
   FROM DW_ANALYTICS.DW_EB_USER t1
   WHERE EXISTS
       (SELECT 1
        FROM CINS_TMP_CUSTOMER_{RPT_DT_TBL} t2
        WHERE t1.CUSTOMER_CDE=t2.CUSTOMER_CDE)
     AND TO_DATE(ACTIVATE_DT) <= TO_DATE('{RPT_DT}', 'DD-MM-YY')
     AND ACTIVATE_DT != TO_DATE('01/01/2400', 'DD/MM/YYYY')
   GROUP BY customer_cde) A