/*
Table Name: CINS_TMP_DATA_RPT_CARD_{RPT_DT_TBL}
Derived From: 
    DW_ANALYTICS.DATA_RPT_CARD_493:
        - CUSTOMER_CDE
        - CARD_CDE
        - PROCESS_DT
        - TT_CARD_LIMIT
    CINS_TMP_CUSTOMER_{RPT_DT_TBL}:
        - CUSTOMER_CDE
    CINS_TMP_CARD_DIM_{RPT_DT_TBL}:
        - CARD_CDE
*/
CREATE TABLE CINS_TMP_DATA_RPT_CARD_{RPT_DT_TBL} (
    CUSTOMER_CDE VARCHAR2(25 BYTE),
    CARD_CDE VARCHAR2(25 BYTE),
    PROCESS_DT DATE,
    TT_CARD_LIMIT NUMBER
);


COMMIT;