/*
Table Name: CINS_TMP_LST_{RPT_DT_TBL}
Derived From: 
    CINS_TMP_CREDIT_CARD_TRANSACTION_{RPT_DT_TBL}: 
        - CUSTOMER_CDE
        - PROCESS_DT
    CINS_2M_PART:
        - PRODUCT
        - CUSTOMER_CDE
    DW_ANALYTICS.DW_EB_TRANSACTION_FCT:
        - CUSTOMER_CDE
        - TXN_DT
        - TXN_STATUS
    DW_ANALYTICS.DW_EWALL_TRANSACTION_FCT:
        - CUSTOMER_CDE
        - PROCESS_DT
        - TXN_STATUS
    DW_ANALYTICS.DWA_STMT_EBANK:
        - CUSTOMER_ID
        - PRODUCT_CATEGORY
        - PROCESS_DT
        - TRANSACTION_CODE
    DW_ANALYTICS.TRANSACTION_CODE:
        - INITIATION
        - TRANSACTION_CODE
*/
CREATE TABLE CINS_TMP_LST_{RPT_DT_TBL} (
    PRODUCT VARCHAR(20), 
    CUSTOMER_CDE VARCHAR(20)
);


COMMIT;