/*
Table Name: CINS_TMP_CREDIT_CARD_TRANSACTION_{RPT_DT_TBL}
Derived From: 
    DW_ANALYTICS.DW_CARD_TRANSACTION_FCT:
        - CUSTOMER_CDE
        - CARD_CDE
        - PROCESS_DT
        - APPROVAL_CDE
        - RETRVL_REFNO
        - AMT_BILL
        - ACQ_CNTRY_CDE
        - MERCHANT_CDE
        - TXN_CURR_CDE
        - BILL_CURR_CDE
        - PRODUCT_CDE
        - MCC_CDE
        - TXN_OL_CDE
        - TXN_OM_CDE
        - AMT_FEE
        - TRAN_STATUS
        - COMPANY_KEY
        - SUB_SECTOR_CDE
    CINS_TMP_CUSTOMER_{RPT_DT_TBL}:
        - CUSTOMER_CDE
*/
CREATE TABLE CINS_TMP_CREDIT_CARD_TRANSACTION_{RPT_DT_TBL} (
    CUSTOMER_CDE VARCHAR2(25 BYTE),
    PROCESS_DT DATE,
    APPROVAL_CDE VARCHAR2(25 BYTE),
    RETRVL_REFNO VARCHAR2(25 BYTE),
    AMT_BILL NUMBER,
    ACQ_CNTRY_CDE VARCHAR2(25 BYTE),
    MERCHANT_CDE VARCHAR2(25 BYTE),
    TXN_CURR_CDE VARCHAR2(25 BYTE),
    BILL_CURR_CDE VARCHAR2(25 BYTE),
    PRODUCT_CDE VARCHAR2(25 BYTE),
    TXN_OL_CDE VARCHAR2(25 BYTE),
    MCC_CDE NUMBER,
    TXN_OM_CDE VARCHAR2(25 BYTE),
    AMT_FEE NUMBER
);


COMMIT;