/*
Table Name: CINS_TMP_CUSTOMER_STATUS_{RPT_DT_TBL}
Derived From: 
  DW_ANALYTICS.DW_CUST_PRODUCT_LOC_FCT: 
    - CUST_STATUS
    - PROCESS_DT
    - CUSTOMER_CDE
  CINS_TMP_CUSTOMER_{RPT_DT_TBL}: 
    - CUSTOMER_CDE
*/
CREATE TABLE CINS_TMP_CUSTOMER_STATUS_{RPT_DT_TBL} (
    CUSTOMER_CDE VARCHAR2(25 BYTE),
    RPT_DT VARCHAR2(25 BYTE),
    CUST_STT NUMBER,
    CUST_STT_CHG NUMBER
);


COMMIT;