/*
Table Name: CINS_TMP_EB_MB_CROSSELL_{RPT_DT_TBL}
Derived From: 
    DW_ANALYTICS.DW_EB_USER:
        - CUSTOMER_CDE
        - LOGIN_ALLOWED
        - DEL_FLG
        - PROCESS_DT
        - CORP_ID
        - REC_UPDATE_DT
        - INPUT_DT
    CINS_TMP_CUSTOMER_{RPT_DT_TBL}:
        - CUSTOMER_CDE
*/
CREATE TABLE CINS_TMP_EB_MB_CROSSELL_{RPT_DT_TBL} (
    CUSTOMER_CDE VARCHAR2(25 BYTE),
    CORP_ID VARCHAR2(100 BYTE),
    INPUT_DT DATE
);


COMMIT;