/*
Table Name: CINS_TMP_CARD_DIM_{RPT_DT_TBL}
Derived From: 
  DW_ANALYTICS.DW_CARD_MASTER_DIM: 
    - CARD_CDE
    - STATUS_CDE
    - PLASTIC_CDE 
*/
CREATE TABLE CINS_TMP_CARD_DIM_{RPT_DT_TBL} (
    CARD_CDE VARCHAR2(25 BYTE)
);


COMMIT;