/*
Table Name: CINS_TMP_CREDIT_CARD_LOAN_6M_{RPT_DT_TBL}
Derived From: 
    DW_ANALYTICS.DW_CARD_MASTER_DIM:
        - CUSTOMER_CDE
        - CARD_CDE
        - ACTIVATION_DT
        - PLASTIC_CDE
        - STATUS_CDE
*/
CREATE TABLE CINS_TMP_CREDIT_CARD_LOAN_6M_{RPT_DT_TBL} (
    CUSTOMER_CDE VARCHAR2(25 BYTE),
    RN NUMBER
);


COMMIT;