/*
Table Name: CINS_CUSTOMER_DIM
Derived From: 
  DW_ANALYTICS.DW_CUSTOMER_DIM: 
    - CUSTOMER_CDE
    - ACTIVE
    - COMPANY_KEY
    - SUB_SECTOR_CDE
*/
CREATE TABLE CINS_CUSTOMER_DIM (
    CUSTOMER_CDE VARCHAR2(25 BYTE)
);


COMMIT;