/*
Table Name: CINS_TMP_CREDIT_CARD_LOAN_6M_{RPT_DT_TBL}
Derived From: 
    DW_ANALYTICS.DW_CARD_MASTER_DIM:
        - CUSTOMER_CDE
        - CARD_CDE
        - ACTIVATION_DT
        - PLASTIC_CDE
        - STATUS_CDE
*/
INSERT INTO CINS_TMP_CREDIT_CARD_LOAN_6M_{RPT_DT_TBL}
SELECT CUSTOMER_CDE, ROW_NUMBER() OVER(PARTITION BY CUSTOMER_CDE ORDER BY ACTIVATION_DT DESC) RN
FROM DW_ANALYTICS.DW_CARD_MASTER_DIM
WHERE SUBSTR(CARD_CDE,1,1) = '3' 
    AND PLASTIC_CDE = ' ' 
    AND STATUS_CDE = ' '
    AND TO_DATE('{RPT_DT}','DD-MM-YY') - TO_DATE(ACTIVATION_DT) >= 180
