TABLE:
  - CINS_TMP_CUSTOMER
  - CINS_TMP_CARD_DIM
  - CINS_FEATURE_STORE_V2
  - CINS_2M_PART
  - CINS_TMP_LST
  - CINS_TMP_CREDIT_CARD_LOAN_6M
  - CINS_TMP_CREDIT_CARD_TRANSACTION
  - CINS_TMP_CUSTOMER_STATUS
  - CINS_TMP_DATA_RPT_CARD
  - CINS_TMP_DATA_RPT_LOAN
  - CINS_TMP_EB_MB_CROSSELL
  - CINS_TMP_POS_MERCHANT_6M
  - CINS_TMP_POS_MERCHANT_AMT_6M
  - CINS_TMP_POS_TERMINAL_6M
  - CINS_TMP_POS_TERMINAL_AMT_6M
FEATURE:
  - AGE
  - CARD_AVG_BAL_3M
  - CARD_AVG_BAL_6M
  - CARD_BRANCH_LOC_3M
  - CARD_BRANCH_LOC_6M
  - CARD_CREDIT_AMOUNT_CASH_LESS_30_6M
  - CARD_CREDIT_AMOUNT_SALE_MCC_VANG_50_6M
  - CARD_CREDIT_CASH_RATIO_30_6M
  - CARD_CREDIT_CT_CARD_ACTIVE
  - CARD_CREDIT_CT_CONSUMP_LOAN
  - CARD_CREDIT_CT_INACTIVE_ALL
  - CARD_CREDIT_DAY_SINCE_LTST_TXN
  - CARD_CREDIT_DEBT_GRP_6M
  - CARD_CREDIT_INACTIVE
  - CARD_CREDIT_LIMIT_TXN_1M
  - CARD_CREDIT_LIMIT_TXN_3M
  - CARD_CREDIT_LIMIT_TXN_6M
  - CARD_CREDIT_MAX_BRAND_LIMIT
  - CARD_CREDIT_MAX_CLASS
  - CARD_CREDIT_MAX_LIMIT
  - CARD_CREDIT_NON_DEBT_GRP_6M
  - CARD_CREDIT_TXN_CT_12M
  - CARD_CREDIT_TXN_CT_1M
  - CARD_CREDIT_TXN_CT_3M
  - CARD_CREDIT_TXN_CT_6M
  - CARD_CREDIT_TXN_DOM_CT_12M
  - CARD_CREDIT_TXN_DOM_CT_1M
  - CARD_CREDIT_TXN_DOM_CT_3M
  - CARD_CREDIT_TXN_DOM_CT_6M
  - CARD_CREDIT_TXN_INTER_CT_12M
  - CARD_CREDIT_TXN_INTER_CT_1M
  - CARD_CREDIT_TXN_INTER_CT_3M
  - CARD_CREDIT_TXN_INTER_CT_6M
  - CARD_CREDIT_TXN_OFFLINE_CT_12M
  - CARD_CREDIT_TXN_OFFLINE_CT_1M
  - CARD_CREDIT_TXN_OFFLINE_CT_3M
  - CARD_CREDIT_TXN_OFFLINE_CT_6M
  - CARD_CREDIT_TXN_ONLINE_CT_12M
  - CARD_CREDIT_TXN_ONLINE_CT_1M
  - CARD_CREDIT_TXN_ONLINE_CT_3M
  - CARD_CREDIT_TXN_ONLINE_CT_6M
  - CARD_CT_VAR_BRANCH_3M
  - CARD_FAV_BRANCH_LOC_6M
  - CASA_ACCT_ACTIVE_CT_12M
  - CASA_ACCT_COMBO_CT_36M
  - CASA_ACCT_CT_36M
  - CASA_ACCT_PAYROLL_CT_36M
  - CASA_BAL_AVG_12M
  - CASA_BAL_AVG_1M
  - CASA_BAL_AVG_3M
  - CASA_BAL_AVG_6M
  - CASA_BAL_MAX_12M
  - CASA_BAL_MAX_1M
  - CASA_BAL_MAX_3M
  - CASA_BAL_MAX_6M
  - CASA_BAL_MIN_12M
  - CASA_BAL_MIN_1M
  - CASA_BAL_MIN_3M
  - CASA_BAL_MIN_6M
  - CASA_BAL_SUM_12M
  - CASA_BAL_SUM_1M
  - CASA_BAL_SUM_3M
  - CASA_BAL_SUM_6M
  - CASA_BAL_SUM_NOW
  - CASA_CT_VAR_BRANCH_REG_3M
  - CASA_DAY_SINCE_LAST_TXN_CT_36M
  - CASA_TXN_AMT_AVG_12M
  - CASA_TXN_AMT_AVG_1M
  - CASA_TXN_AMT_AVG_3M
  - CASA_TXN_AMT_AVG_6M
  - CASA_TXN_AMT_MAX_12M
  - CASA_TXN_AMT_MAX_1M
  - CASA_TXN_AMT_MAX_3M
  - CASA_TXN_AMT_MAX_6M
  - CASA_TXN_AMT_MIN_12M
  - CASA_TXN_AMT_MIN_1M
  - CASA_TXN_AMT_MIN_3M
  - CASA_TXN_AMT_MIN_6M
  - CASA_TXN_AMT_SUM_12M
  - CASA_TXN_AMT_SUM_1M
  - CASA_TXN_AMT_SUM_3M
  - CASA_TXN_AMT_SUM_6M
  - CASA_TXN_CT_12M
  - CASA_TXN_CT_1M
  - CASA_TXN_CT_3M
  - CASA_TXN_CT_6M
  - EB_MBIB_INACTIVE
  - EB_SACOMPAY_INACTIVE
  - GEN_GRP
  - INACTIVE
  - LIFE_STG
  - PROFESSION
  - REACTIVATED