SERVING_FEATURES = [
    'CASA_HOLD','CARD_CREDIT_HOLD','EB_SACOMPAY_HOLD','EB_MBIB_HOLD',
    'LIFE_STG', 'AREA',
    'LOR','CREDIT_SCORE',
    'CASA_BAL_SUM_NOW','CASA_DAY_SINCE_LAST_TXN_CT_36M',
    'CARD_CREDIT_MAX_LIMIT','CARD_CREDIT_SUM_BAL_NOW',
    'EB_SACOMPAY_DAY_SINCE_LTST_LOGIN','EB_SACOMPAY_DAY_SINCE_LTST_TXN','EB_MBIB_DAY_SINCE_ACTIVE',
]

LABEL = 'REACTIVATED'


TEMPLATE_QUERY_RAW_DATA_FROM_FEATURE_STORE = """
SELECT CUSTOMER_CDE, FTR_NM, FTR_VAL, RPT_DT 
FROM CINS_FEATURE_STORE_REACTIVATED
WHERE RPT_DT = TO_DATE('%s', 'DD-MM-YY')
AND FTR_NM = '%s'
"""

TEMPLATE_QUERY_CHECK_RPT_DT_EXIST ="""
SELECT COUNT(1) FROM CINS_FEATURE_STORE_REACTIVATED
WHERE RPT_DT = TO_DATE('%s', 'DD-MM-YY')"""