QUERY_CUSTOMER_CDE_RPT_DT = """
    SELECT CUSTOMER_CDE FROM CINS_TMP_CUSTOMER_%s
"""

QUERY_RAW_DATA_FROM_FEATURE_STORE = """
    SELECT CUSTOMER_CDE, FTR_NM, FTR_VAL, RPT_DT 
    FROM CINS_FEATURE_STORE_REACTIVATED
    WHERE RPT_DT = TO_DATE('%s', 'DD-MM-YY')
    AND FTR_NM = '%s'
"""