/*
Feature Name: AGE
Derived From: 
  DW_ANALYTICS.DW_CUSTOMER_DIM: 
    - CUSTOMER_CDE
    - ACTIVE
    - COMPANY_KEY
    - SUB_SECTOR_CDE
    - CUS_OPEN_DT
    - BIRTHDAY
Tags: 
  - DEMOGRAPHIC
TW: ALL
*/

INSERT INTO {TBL_NM}
SELECT TMP.CUSTOMER_CDE,
    'AGE' AS FTR_NM,
    FLOOR(MONTHS_BETWEEN(TO_DATE('{RPT_DT}', 'DD-MM-YY'), BIRTHDAY)/12) AS FTR_VAL,
    TO_DATE('{RPT_DT}', 'DD-MM-YY') AS RPT_DT,
    CURRENT_TIMESTAMP AS ADD_TSTP
FROM DW_ANALYTICS.DW_CUSTOMER_DIM DIM
RIGHT JOIN CINS_TMP_CUSTOMER_{RPT_DT_TBL} TMP ON DIM.CUSTOMER_CDE = TMP.CUSTOMER_CDE
WHERE ACTIVE = 1
    AND COMPANY_KEY = 1
    AND SUB_SECTOR_CDE IN ('1700','1602')
    AND CUS_OPEN_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')