/*
Feature Name: CARD_CREDIT_SUM_BAL_NOW
Derived From: DATA_RPT_CARD_493, CINS_TMP_CUSTOMER_{RPT_DT_TBL}
*/
INSERT INTO {TBL_NM}
SELECT CUSTOMER_CDE,
    'CARD_CREDIT_SUM_BAL_NOW' AS FTR_NM,
    SUM(TT_ORIGINAL_BALANCE) AS FTR_VAL,
    TO_DATE('{RPT_DT}', 'DD-MM-YY') AS RPT_DT,
    CURRENT_TIMESTAMP AS ADD_TSTP
FROM
  (SELECT BAL.*, ROW_NUMBER() OVER(PARTITION BY CUSTOMER_CDE, CARD_CDE ORDER BY PROCESS_DT DESC) RN
   FROM
     (SELECT CC.CUSTOMER_CDE,
             CARD_CDE,
             TT_ORIGINAL_BALANCE,
             PROCESS_DT
      FROM DW_ANALYTICS.DATA_RPT_CARD_493 CC
      RIGHT JOIN CINS_TMP_CUSTOMER_{RPT_DT_TBL} TMP ON CC.CUSTOMER_CDE = TMP.CUSTOMER_CDE
      WHERE CC.PROCESS_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')
      AND CARD_CDE LIKE '3%' ) BAL) BAL
WHERE RN = 1
GROUP BY CUSTOMER_CDE