/*
Feature Name: CARD_CREDIT_MAX_LIMIT
Derived From: DATA_RPT_CARD_493, CINS_TMP_CUSTOMER_{RPT_DT_TBL}, CINS_TMP_CARD_DIM_{RPT_DT_TBL}
*/
INSERT INTO {TBL_NM}
SELECT DIM.CUSTOMER_CDE,
       'CARD_CREDIT_MAX_LIMIT' AS FTR_NM,
       MAX(TT_CARD_LIMIT) AS FTR_VAL,
       TO_DATE('{RPT_DT}', 'DD-MM-YY') AS RPT_DT,
       CURRENT_TIMESTAMP AS ADD_TSTP
FROM DW_ANALYTICS.DATA_RPT_CARD_493 DIM
RIGHT JOIN CINS_TMP_CUSTOMER_{RPT_DT_TBL} TMP ON DIM.CUSTOMER_CDE = TMP.CUSTOMER_CDE
WHERE SUBSTR(DIM.CARD_CDE, 1, 1) = '3'
  AND DIM.CARD_CDE IN
    (SELECT CARD_CDE FROM CINS_TMP_CARD_DIM_{RPT_DT_TBL})
  AND DIM.PROCESS_DT >= ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -36)
  AND DIM.PROCESS_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')
GROUP BY DIM.CUSTOMER_CDE