/*
Feature Name: CASA_BAL_SUM_NOW
Derived From: 
    DW_DEPOSIT_FCT:
        - ACTUAL_BAL_LCL
        - CATEGORY_CDE
        - CUSTOMER_CDE
        - PROCESS_DT 
    CINS_TMP_CUSTOMER_{RPT_DT_TBL}:
        - CUSTOMER_CDE
Tags:
    - CASA
    - MONETARY
TW: NOW
*/
INSERT INTO {TBL_NM}
SELECT
    CS.CUSTOMER_CDE,
    'CASA_BAL_SUM_NOW' AS FTR_NM,
    SUM(CS.ACTUAL_BAL_LCL) AS FTR_VAL,
    TO_DATE('{RPT_DT}', 'DD-MM-YY') AS RPT_DT,
    CURRENT_TIMESTAMP AS ADD_TSTP
FROM DW_ANALYTICS.DW_DEPOSIT_FCT CS
RIGHT JOIN CINS_TMP_CUSTOMER_{RPT_DT_TBL} TMP ON CS.CUSTOMER_CDE = TMP.CUSTOMER_CDE
WHERE CS.CATEGORY_CDE LIKE '10__'
    AND CS.PROCESS_DT = (
        SELECT MAX(PROCESS_DT)
        FROM DW_ANALYTICS.DW_DEPOSIT_FCT
        WHERE PROCESS_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')
          AND CATEGORY_CDE LIKE '10__'
    )
GROUP BY CS.CUSTOMER_CDE;
