/* 
Feature Name: CASA_DAY_SINCE_LAST_TXN_CT_36M
Derived From: 
  DW_ANALYTICS.DWA_STMT_EBANK: 
    - CUSTOMER_ID
    - PROCESS_DT
    - PRODUCT_CATEGORY
    - TRANSACTION_CODE
  DW_ANALYTICS.TRANSACTION_CODE: 
    - TRANSACTION_CODE
    - INITIATION
  CINS_TMP_CUSTOMER_{RPT_DT_TBL}:
    - CUSTOMER_CDE
Tags: 
  - CASA
  - RECENCY
TW: 36M
*/ 
INSERT INTO {TBL_NM}
WITH 
T0 AS (
    SELECT * FROM CINS_TMP_CUSTOMER_{RPT_DT_TBL}
),
T1 AS (
    SELECT * FROM DW_ANALYTICS.DWA_STMT_EBANK
    WHERE PROCESS_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')
    AND PROCESS_DT >= ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -36)
    AND PRODUCT_CATEGORY LIKE '10__' 
),
T2 AS (
    SELECT * FROM DW_ANALYTICS.TRANSACTION_CODE
    WHERE INITIATION = 'CUSTOMER'
),
T3 AS (
    SELECT *
    FROM T0
    LEFT JOIN T1 ON T0.CUSTOMER_CDE = T1.CUSTOMER_ID
    LEFT JOIN T2 ON T1.TRANSACTION_CODE = T2.TRANSACTION_CODE)
SELECT 
    CUSTOMER_CDE AS CUSTOMER_CDE,
    'CASA_DAY_SINCE_LAST_TXN_CT_36M' AS FTR_NM,
    TO_DATE('{RPT_DT}', 'DD-MM-YY') - NVL(MAX(PROCESS_DT), ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -36)) AS FTR_VAL,
    TO_DATE('{RPT_DT}', 'DD-MM-YY') AS RPT_DT,
    CURRENT_TIMESTAMP AS ADD_TSTP
FROM T3
GROUP BY CUSTOMER_CDE;