/*
Feature Name: CREDIT_SCORE
Derived From: STG_CRS_CUSTOMER_SCORE, DW_CUSTOMER_DIM
*/
INSERT INTO {TBL_NM}
WITH 
T0 AS (
    SELECT 
        TRIM(' ' FROM(CUSTOMER_CDE))CUSTOMER_CDE,
        NVL(FINANCIALSCORE, NONFINANCIALSCORE) CREDIT_SCORE,
        RANK()OVER(PARTITION BY CUSTOMER_CDE ORDER BY DATE_1 DESC)RANK_SCORE, 
        DATE_1,
        PROCESS_DATE
     FROM DW_ANALYTICS.STG_CRS_CUSTOMER_SCORE
),
T1 AS (
    SELECT 
        CUSTOMER_CDE,
        CREDIT_SCORE,
        DATE_1,
        PROCESS_DATE,
        ROW_NUMBER() OVER(PARTITION BY CUSTOMER_CDE ORDER BY CREDIT_SCORE DESC) RN
    FROM T0
    WHERE RANK_SCORE = 1
    AND TO_DATE(DATE_1) < TO_DATE('31-12-23', 'DD-MM-YY')
),
T2 AS (
    SELECT CUSTOMER_CDE
    FROM DW_ANALYTICS.DW_CUSTOMER_DIM
    WHERE SUB_SECTOR_CDE IN ('1700', '1602')
    AND ACTIVE = '1'
    AND COMPANY_KEY = '1'
),
T3 AS (
    SELECT T1.CUSTOMER_CDE, T1.CREDIT_SCORE
    FROM T1 RIGHT JOIN T2 ON T1.CUSTOMER_CDE = T2.CUSTOMER_CDE
    WHERE T1.RN = 1
),
T5 AS (
    SELECT 
        T3.CUSTOMER_CDE,
        CASE
          WHEN T3.CREDIT_SCORE IS NULL THEN 0
          ELSE T3.CREDIT_SCORE
        END CREDIT_SCORE
    FROM T3 
    RIGHT JOIN CINS_TMP_CUSTOMER_{RPT_DT_TBL} T4 ON T3.CUSTOMER_CDE = T4.CUSTOMER_CDE
    WHERE T3.CUSTOMER_CDE IS NOT NULL
    AND T4.CUSTOMER_CDE IS NOT NULL
)
SELECT 
    CUSTOMER_CDE,
    'CREDIT_SCORE' AS FTR_NM,
    CREDIT_SCORE AS FTR_VAL,
    TO_DATE('{RPT_DT}', 'DD-MM-YY') AS RPT_DT,
    CURRENT_TIMESTAMP AS ADD_TSTP
FROM T5