/*
Feature Name: EB_MBIB_DAY_SINCE_ACTIVE
Derived From: DW_EB_USER, CINS_TMP_CUSTOMER_{RPT_DT_TBL}
*/
INSERT INTO {TBL_NM}
SELECT CUSTOMER_CDE,
  'EB_MBIB_DAY_SINCE_ACTIVE' AS FTR_NM,
  TO_DATE('{RPT_DT}', 'DD-MM-YY') - ACTIVATE_DATE AS FTR_VAL,
  TO_DATE('{RPT_DT}', 'DD-MM-YY') AS RPT_DT,
  CURRENT_TIMESTAMP AS ADD_TSTP
FROM
  (SELECT T1.CUSTOMER_CDE,
          MIN(ACTIVATE_DT) AS ACTIVATE_DATE
   FROM DW_ANALYTICS.DW_EB_USER T1
   RIGHT JOIN CINS_TMP_CUSTOMER_{RPT_DT_TBL} TMP ON T1.CUSTOMER_CDE = TMP.CUSTOMER_CDE
   WHERE TO_DATE(ACTIVATE_DT) <= TO_DATE('{RPT_DT}', 'DD-MM-YY')
     AND ACTIVATE_DT != TO_DATE('01/01/2400', 'DD/MM/YYYY')
   GROUP BY T1.CUSTOMER_CDE) A