/*
Feature Name: EB_MBIB_HOLD
Derived From: DW_EB_USER, CINS_TMP_CUSTOMER_{RPT_DT_TBL}
*/
INSERT INTO {TBL_NM}
SELECT DISTINCT DIM.CUSTOMER_CDE,
    'EB_MBIB_HOLD' AS FTR_NM,
    1 AS FTR_VAL,
    TO_DATE('{RPT_DT}', 'DD-MM-YY') AS RPT_DT,
    CURRENT_TIMESTAMP AS ADD_TSTP
FROM DW_ANALYTICS.DW_EB_USER DIM
RIGHT JOIN CINS_TMP_CUSTOMER_{RPT_DT_TBL} TMP ON DIM.CUSTOMER_CDE = TMP.CUSTOMER_CDE
WHERE DIM.PROCESS_DT IN
    (SELECT MAX(PROCESS_DT)
     FROM DW_ANALYTICS.DW_EB_USER
     WHERE PROCESS_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY') )
  AND DIM.DEL_FLG = 'N'