/*
Feature Name: EB_SACOMPAY_DAY_SINCE_LTST_TXN
Derived From: DW_EWALL_TRANSACTION_FCT, CINS_TMP_CUSTOMER_{RPT_DT_TBL}
*/
INSERT INTO {TBL_NM}
SELECT CUSTOMER_CDE,
  'EB_SACOMPAY_DAY_SINCE_LTST_TXN' AS FTR_NM,
  TO_DATE('{RPT_DT}', 'DD-MM-YY') - NVL(MAX(PROCESS_DT), ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -36)) AS FTR_VAL,
  TO_DATE('{RPT_DT}', 'DD-MM-YY') AS RPT_DT,
  CURRENT_TIMESTAMP AS ADD_TSTP
FROM DW_ANALYTICS.DW_EWALL_TRANSACTION_FCT FCT
RIGHT JOIN CINS_TMP_CUSTOMER_{RPT_DT_TBL} TMP ON FCT.CUSTOMER_CDE = TMP.CUSTOMER_CDE
WHERE PROCESS_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')
  AND PROCESS_DT >= ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -36)
  AND TXN_STATUS = 'S'
GROUP BY CUSTOMER_CDE