/*
Feature Name: LOR
Derived From: DW_CUSTOMER_DIM
*/
INSERT INTO {TBL_NM}
SELECT DIM.CUSTOMER_CDE,
    'LOR' AS FTR_NM,
    TO_DATE('{RPT_DT}', 'DD-MM-YY') - TO_DATE(CUS_OPEN_DT) AS FTR_VAL,
    TO_DATE('{RPT_DT}', 'DD-MM-YY') AS RPT_DT,
    CURRENT_TIMESTAMP AS ADD_TSTP
FROM DW_ANALYTICS.DW_CUSTOMER_DIM DIM
RIGHT JOIN CINS_TMP_CUSTOMER_{RPT_DT_TBL} TMP ON DIM.CUSTOMER_CDE = TMP.CUSTOMER_CDE
WHERE DIM.SUB_SECTOR_CDE IN ('1700', '1602')
  AND DIM.ACTIVE = '1'
  AND DIM.COMPANY_KEY = '1'
  AND TO_DATE(DIM.CUS_OPEN_DT) <= TO_DATE('{RPT_DT}', 'DD-MM-YY')