/*
Feature Name: AGE
Derived From: 
  DW_ANALYTICS.DW_CUSTOMER_DIM: CUSTOMER_CDE, ACTIVE, COMPANY_KEY, SUB_SECTOR_CDE, CUS_OPEN_DT,BIRTHDAY
Tags: DEMOGRAPHIC
*/

INSERT INTO {TBL_NM}
SELECT CUSTOMER_CDE,
    'AGE' FTR_NM,
    FLOOR(MONTHS_BETWEEN(TO_DATE('{RPT_DT}', 'DD-MM-YY'), BIRTHDAY)/12) FTR_VAL,
    TO_DATE('{RPT_DT}', 'DD-MM-YY') AS RPT_DT,
    CURRENT_TIMESTAMP ADD_TSTP
FROM DW_ANALYTICS.DW_CUSTOMER_DIM
WHERE ACTIVE = 1
    AND COMPANY_KEY = 1
    AND SUB_SECTOR_CDE IN ('1700','1602')
    AND CUS_OPEN_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')