/*
Feature Name: CASA_CT_VAR_BRANCH_REG_3M
Derived From: 
  DW_ACCOUNT_MASTER_DIM:
    - CUSTOMER_CDE
    - ACCT_ID
    - UPDATE_DT
    - OPEN_DT
    - ACTIVE
    - COMPANY_KEY
    - CATEGORY_CDE
  CINS_TMP_CUSTOMER_{RPT_DT_TBL}:
    - CUSTOMER_CDE
    - RPT_DT
    - ADD_TSTP
Tags:
  - CASA
TW: 3M
*/
INSERT INTO {TBL_NM}
SELECT
    T.CUSTOMER_CDE,
    'CASA_CT_VAR_BRANCH_REG_3M' AS FTR_NM,
    COUNT(DISTINCT T.SUB_BRANCH_CDE) AS FTR_VAL,
    TO_DATE('{RPT_DT}', 'DD-MM-YY') AS RPT_DT,
    CURRENT_TIMESTAMP AS ADD_TSTP
FROM (
    SELECT
        AMD.CUSTOMER_CDE,
        AMD.SUB_BRANCH_CDE,
        ROW_NUMBER() OVER (PARTITION BY AMD.CUSTOMER_CDE, AMD.ACCT_ID ORDER BY AMD.UPDATE_DT DESC) AS RN
    FROM DW_ANALYTICS.DW_ACCOUNT_MASTER_DIM AMD
    JOIN CINS_TMP_CUSTOMER_{RPT_DT_TBL} TMP
        ON AMD.CUSTOMER_CDE = TMP.CUSTOMER_CDE
    WHERE AMD.OPEN_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')
        AND AMD.ACTIVE = 1
        AND AMD.OPEN_DT >= ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -3)
        AND AMD.COMPANY_KEY = 1
        AND AMD.CATEGORY_CDE LIKE '10__'
) T
WHERE T.RN = 1
GROUP BY T.CUSTOMER_CDE;