/*
Feature Name: CASA_INACTIVE
Derived From: 
  DW_ANALYTICS.DW_CUSTOMER_DIM: 
    - ACTIVE
    - COMPANY_KEY
    - SUB_SECTOR_CDE
    - CUS_OPEN_DT
    - CUSTOMER_CDE
  DW_ANALYTICS.DWA_STMT_EBANK: 
    - CUSTOMER_ID
    - PRODUCT_CATEGORY
    - TRANSACTION_CODE
    - PROCESS_DT
  DW_ANALYTICS.TRANSACTION_CODE: 
    - TRANSACTION_CODE,
    - INITIATION 
TW: 36M
Tags: 
  - LABEL 
*/
INSERT INTO {TBL_NM}
WITH 
T1 AS (
    SELECT CUSTOMER_CDE
    FROM DW_ANALYTICS.DW_CUSTOMER_DIM
    WHERE ACTIVE = 1
      AND COMPANY_KEY = 1
      AND SUB_SECTOR_CDE IN ('1700','1602')
      AND CUS_OPEN_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')
      AND CUSTOMER_CDE IS NOT NULL
),
T2 AS (
    SELECT DISTINCT CUSTOMER_ID
    FROM DW_ANALYTICS.DWA_STMT_EBANK TXN
    JOIN
       (SELECT TRANSACTION_CODE
        FROM DW_ANALYTICS.TRANSACTION_CODE
        WHERE INITIATION = 'CUSTOMER') TC ON TXN.TRANSACTION_CODE = TC.TRANSACTION_CODE
    WHERE PRODUCT_CATEGORY LIKE '10__'
      AND PROCESS_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')
      AND PROCESS_DT >= ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -12)
      AND CUSTOMER_ID IS NOT NULL
),
T3 AS (
    SELECT DISTINCT CUSTOMER_ID
    FROM DW_ANALYTICS.DWA_STMT_EBANK TXN
    JOIN
      (SELECT TRANSACTION_CODE
      FROM DW_ANALYTICS.TRANSACTION_CODE
      WHERE INITIATION = 'CUSTOMER') TC ON TXN.TRANSACTION_CODE = TC.TRANSACTION_CODE
    WHERE PRODUCT_CATEGORY LIKE '10__'
      AND PROCESS_DT < ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -12)
      AND PROCESS_DT >= ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -36)
      AND CUSTOMER_ID IS NOT NULL
),
T4 AS (
    SELECT DISTINCT T1.CUSTOMER_CDE
    FROM T1
    LEFT JOIN T2 ON T1.CUSTOMER_CDE = T2.CUSTOMER_ID
    LEFT JOIN T3 ON T1.CUSTOMER_CDE = T3.CUSTOMER_ID
    WHERE T2.CUSTOMER_ID IS NULL 
      AND T3.CUSTOMER_ID IS NOT NULL
)

SELECT CUSTOMER_CDE,
    'CASA_INACTIVE' FTR_NM,
    1 FTR_VAL,
    TO_DATE('{RPT_DT}', 'DD-MM-YY') AS RPT_DT,
    CURRENT_TIMESTAMP ADD_TSTP 
FROM T4;