/*
Feature Name: CASA_CT_VAR_BRANCH_REG_3M
Derived From: DW_ACCOUNT_MASTER_DIM, CINS_TMP_CUSTOMER_{RPT_DT_TBL}
*/
INSERT INTO {TBL_NM}
SELECT
    T.CUSTOMER_CDE,
    'CASA_CT_VAR_BRANCH_REG_3M' AS FTR_NM,
    COUNT(DISTINCT T.sub_branch_cde) AS FTR_VAL,
    TO_DATE('{RPT_DT}', 'DD-MM-YY') AS RPT_DT,
    CURRENT_TIMESTAMP AS ADD_TSTP
FROM (
    SELECT
        AMD.CUSTOMER_CDE,
        AMD.sub_branch_cde,
        ROW_NUMBER() OVER (PARTITION BY AMD.CUSTOMER_CDE, AMD.acct_id ORDER BY AMD.update_dt DESC) AS rn
    FROM DW_ANALYTICS.DW_ACCOUNT_MASTER_DIM AMD
    JOIN CINS_TMP_CUSTOMER_{RPT_DT_TBL} TMP
        ON AMD.CUSTOMER_CDE = TMP.CUSTOMER_CDE
    WHERE AMD.open_dt < TO_DATE('{RPT_DT}', 'DD-MM-YY')
        AND AMD.active = 1
        AND AMD.open_dt >= ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -3)
        AND AMD.company_key = 1
        AND AMD.category_cde LIKE '10__'
) T
WHERE T.rn = 1
GROUP BY T.CUSTOMER_CDE;
