/*
Feature Name: EB_MBIB_INACTIVE
Derived From: 
  DW_ANALYTICS.DW_EB_TRANSACTION_FCT: 
    - CUSTOMER_CDE
    - TXN_DT
    - TXN_STATUS
  DW_ANALYTICS.DW_CUSTOMER_DIM: 
    - CUSTOMER_CDE
    - ACTIVE
    - COMPANY_KEY
    - SUB_SECTOR_CDE
TW: 36M
Tags: 
  - LABEL, EBANKING
*/
INSERT INTO {TBL_NM}
WITH 
T1 AS (
  SELECT CUSTOMER_CDE
  FROM DW_ANALYTICS.DW_CUSTOMER_DIM
  WHERE ACTIVE = 1
    AND COMPANY_KEY = 1
    AND SUB_SECTOR_CDE IN ('1700','1602')
),
T2 AS (
  SELECT DISTINCT CUSTOMER_CDE
  FROM DW_ANALYTICS.DW_EB_TRANSACTION_FCT
  WHERE TXN_STATUS = 'SUC'
    AND TXN_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')
    AND TXN_DT >= ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -12)
    AND CUSTOMER_CDE IS NOT NULL
),
T3 AS (
  SELECT DISTINCT CUSTOMER_CDE
  FROM DW_ANALYTICS.DW_EB_TRANSACTION_FCT
  WHERE TXN_STATUS = 'SUC'
    AND TXN_DT < ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -12)
    AND TXN_DT >= ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -36)
    AND CUSTOMER_CDE IS NOT NULL
),
T4 AS (
  SELECT T1.CUSTOMER_CDE
  FROM T1
  LEFT JOIN T2 ON T1.CUSTOMER_CDE = T2.CUSTOMER_CDE
  LEFT JOIN T3 ON T1.CUSTOMER_CDE = T3.CUSTOMER_CDE
  WHERE T2.CUSTOMER_CDE IS NULL
      AND T3.CUSTOMER_CDE IS NOT NULL
)
SELECT CUSTOMER_CDE,
  'EB_MBIB_INACTIVE' FTR_NM,
  1 FTR_VAL,
  TO_DATE('{RPT_DT}', 'DD-MM-YY') AS RPT_DT,
  CURRENT_TIMESTAMP ADD_TSTP
FROM T4;