/*
Feature Name: INACTIVE
Derived From: 
  CINS_TMP_CUSTOMER_STATUS_{RPT_DT_TBL}: CUSTOMER_CDE, CUST_STT, RPT_DT
Tags: LABEL, 
*/
INSERT INTO {TBL_NM}
SELECT CUSTOMER_CDE,
       'INACTIVE' FTR_NM,
       CASE
           WHEN CUST_STT = 1 THEN 1
           WHEN CUST_STT = 2 THEN 0
       END FTR_VAL,
       TO_DATE('{RPT_DT}', 'DD-MM-YY') AS RPT_DT,
       CURRENT_TIMESTAMP ADD_TSTP
FROM CINS_TMP_CUSTOMER_STATUS_{RPT_DT_TBL}
WHERE CUST_STT >= 1
  AND RPT_DT = TO_DATE('{RPT_DT}', 'DD-MM-YY')