/*
Feature Name: PROFESSION
Derived From: 
  DW_ANALYTICS.DW_CUSTOMER_DIM: CUSTOMER_CDE,
    - ACTIVE
    - COMPANY_KEY
    - SUB_SECTOR_CDE
    - CUS_OPEN_DT
    - SUB_INDUSTRY_CDE
  DW_ANALYTICS.DW_INDUSTRY_DIM: 
    - SUB_INDUSTRY_CDE
Tags: 
  - DEMOGRAPHIC
*/
INSERT INTO {TBL_NM}
SELECT CUSTOMER_CDE,
  'PROFESSION' FTR_NM,
  INDUSTRY_GROUP_NAME_VN FTR_VAL,
  TO_DATE('{RPT_DT}', 'DD-MM-YY') AS RPT_DT,
  CURRENT_TIMESTAMP ADD_TSTP
FROM DW_ANALYTICS.DW_CUSTOMER_DIM A
JOIN DW_ANALYTICS.DW_INDUSTRY_DIM B ON A.SUB_INDUSTRY_CDE = B.SUB_INDUSTRY_CDE
WHERE A.ACTIVE = 1
  AND A.COMPANY_KEY = 1
  AND A.SUB_SECTOR_CDE IN ('1700','1602')
  AND CUS_OPEN_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')