/*
Feature Name: REACTIVATED
Derived From: 
  CINS_TMP_CUSTOMER_STATUS_{RPT_DT_TBL}: CUSTOMER_CDE, CUST_STT, CUST_STT_CHG, RPT_DT
Tags: LABEL, 
*/
INSERT INTO {TBL_NM}
SELECT CUSTOMER_CDE,
       'REACTIVATED' FTR_NM,
       1 FTR_VAL,
       TO_DATE('{RPT_DT}', 'DD-MM-YY') AS RPT_DT,
       CURRENT_TIMESTAMP ADD_TSTP
FROM CINS_TMP_CUSTOMER_STATUS_{RPT_DT_TBL}
WHERE CUST_STT = 2
  AND CUST_STT_CHG = 1
  AND RPT_DT = TO_DATE('{RPT_DT}', 'DD-MM-YY')