CREATE TABLE CINS_FEATURE_STORE_REACTIVATED (	
    CUSTOMER_CDE VARCHAR2(30 BYTE),
    FTR_NM VARCHAR2(200 BYTE),
    FTR_VAL VARCHAR2(2000 BYTE),
    RPT_DT VARCHAR2(50 BYTE),
    ADD_TSTP TIMESTAMP (6)
);