/*
Feature Name: CARD_CREDIT_CT_INACTIVE_ALL
Derived From: CINS_TMP_CREDIT_CARD_TRANSACTION_{RPT_DT_TBL}
*/
INSERT INTO {TBL_NM}
SELECT CUSTOMER_CDE,
       'CARD_CREDIT_CT_INACTIVE_ALL' FTR_NM,
                                     COUNT(*) FTR_VAL,
                                     TO_DATE('{RPT_DT}', 'DD-MM-YY') AS RPT_DT,
                                     CURRENT_TIMESTAMP ADD_TSTP
FROM
  (SELECT CUSTOMER_CDE,
          NVL(MONTHS_BETWEEN(LEAD(PROCESS_DT) OVER (PARTITION BY CUSTOMER_CDE
                                                    ORDER BY PROCESS_DT), PROCESS_DT), MONTHS_BETWEEN(TO_DATE('{RPT_DT}', 'DD-MM-YY'), PROCESS_DT)) TXN_GAP
   FROM CINS_TMP_CREDIT_CARD_TRANSACTION_{RPT_DT_TBL}
   WHERE PROCESS_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY'))
WHERE TXN_GAP > 3
GROUP BY CUSTOMER_CDE