/*
Feature Name: CARD_CREDIT_INACTIVE
Derived From: DW_CUSTOMER_DIM, DW_CARD_TRANSACTION_FCT, DW_CARD_MASTER_DIM
*/
INSERT INTO {TBL_NM}
SELECT CUSTOMER_CDE,
       'CARD_CREDIT_INACTIVE' FTR_NM,
                              1 FTR_VAL,
                              TO_DATE('{RPT_DT}', 'DD-MM-YY') AS RPT_DT,
                              CURRENT_TIMESTAMP ADD_TSTP
FROM DW_ANALYTICS.DW_CUSTOMER_DIM
WHERE ACTIVE = 1
  AND COMPANY_KEY = 1
  AND SUB_SECTOR_CDE IN ('1700',
                         '1602')
  AND CUSTOMER_CDE IN
    (SELECT CUSTOMER_CDE
     FROM DW_ANALYTICS.DW_CARD_MASTER_DIM
     WHERE CARD_CDE LIKE '3%'
       AND STATUS_CDE = ' '
       AND ACTIVATION_DT < ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -3)
       AND TO_CHAR(ACTIVATION_DT, 'yyyy') > 1900)
  AND CUSTOMER_CDE NOT IN
    (SELECT CUSTOMER_CDE
     FROM DW_ANALYTICS.DW_CARD_TRANSACTION_FCT
     WHERE CARD_CDE LIKE '3%'
       AND TRAN_STATUS = 'S'
       AND POST_DT IS NOT NULL
       AND MCC_CDE NOT IN (0,
                           4829)
       AND MCC_CDE IS NOT NULL
       AND PROCESS_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')
       AND PROCESS_DT >= ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -3))