/*
Feature Name: CARD_CREDIT_HOLD
Derived From: DW_CARD_MASTER_DIM, CINS_TMP_CUSTOMER_{RPT_DT_TBL}
*/
INSERT INTO {TBL_NM}
SELECT CUSTOMER_CDE,
       'CARD_CREDIT_HOLD' AS FTR_NM,
       '1' AS FTR_VAL,
       TO_DATE('{RPT_DT}', 'DD-MM-YY') AS RPT_DT,
       CURRENT_TIMESTAMP AS ADD_TSTP
FROM
  (SELECT DISTINCT CUSTOMER_CDE
   FROM DW_ANALYTICS.DW_CARD_MASTER_DIM
   WHERE SUBSTR(CARD_CDE, 1, 1) = '3'
     AND STATUS_CDE = ' '
     AND BASIC_SUPP_IND = 'B'
     AND TO_CHAR(LAST_RENEWAL_DT) = '01-JAN-00'
     AND ACTIVATION_DT <= TO_DATE('{RPT_DT}', 'DD-MM-YY')
     AND CUSTOMER_CDE IN
       (SELECT CUSTOMER_CDE
        FROM CINS_TMP_CUSTOMER_{RPT_DT_TBL}) )