/*
Feature Name: CARD_CREDIT_UP_SELL_LABEL4_6M
Derived From: CINS_TMP_CREDIT_CARD_TRANSACTION_{RPT_DT_TBL}
*/
INSERT INTO {TBL_NM}
SELECT CUSTOMER_CDE,
       'CARD_CREDIT_UP_SELL_LABEL4_6M' AS FTR_NM,
       FTR_VAL,
       TO_DATE('{RPT_DT}', 'DD-MM-YY') AS RPT_DT,
       CURRENT_TIMESTAMP AS ADD_TSTP
FROM
  (SELECT CUSTOMER_CDE,
          CASE
              WHEN PRODUCT_CDE IN ('4200',
                                   '4201',
                                   '4203',
                                   '4204',
                                   '4205',
                                   '4207',
                                   '4208',
                                   '4210',
                                   '4213',
                                   '4214',
                                   '4215',
                                   '4216',
                                   '4217',
                                   '4218',
                                   '4219',
                                   '4220',
                                   '4221',
                                   '4224',
                                   '4230',
                                   '4231',
                                   '4232',
                                   '4233',
                                   '4234',
                                   '4235',
                                   '4238',
                                   '4240',
                                   '4243',
                                   '4244',
                                   '4245',
                                   '4246',
                                   '4247',
                                   '4248',
                                   '4249',
                                   '4250',
                                   '4251',
                                   '4252',
                                   '4253',
                                   '4254',
                                   '4255',
                                   '4256',
                                   '4269',
                                   '4271',
                                   '4272',
                                   '4277',
                                   '4278',
                                   '7203',
                                   '7204',
                                   '7205',
                                   '7206',
                                   '4600',
                                   '4601',
                                   '4603',
                                   '4604',
                                   '4605',
                                   '4607',
                                   '4608',
                                   '4609',
                                   '4610',
                                   '4611',
                                   '4612',
                                   '4613',
                                   '4614',
                                   '4615',
                                   '4616',
                                   '4617',
                                   '4618',
                                   '5400',
                                   '5401',
                                   '5403',
                                   '5404',
                                   '5405',
                                   '5407',
                                   '5408',
                                   '5409',
                                   '5412',
                                   '5413',
                                   '5414',
                                   '5415',
                                   '5416',
                                   '5417',
                                   '5418',
                                   '5419',
                                   '5420',
                                   '5421',
                                   '5422',
                                   '5423') THEN 1
              ELSE 0
          END AS FTR_VAL,
          ROW_NUMBER() OVER(PARTITION BY CUSTOMER_CDE
                            ORDER BY PROCESS_DT DESC) RN
   FROM CINS_TMP_CREDIT_CARD_TRANSACTION_{RPT_DT_TBL}
   WHERE PRODUCT_CDE IS NOT NULL
     AND ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -6) <= PROCESS_DT
     AND PROCESS_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY') )
WHERE RN = 1
  AND FTR_VAL = 1