/*
Feature Name: CASA_SUM_BAL_NOW
Derived From: DW_DEPOSIT_FCT, CINS_TMP_CUSTOMER_{RPT_DT_TBL}
*/
INSERT INTO {TBL_NM}
SELECT CUSTOMER_CDE,
       'CASA_SUM_BAL_NOW' FTR_NM,
                          SUM(ACTUAL_BAL_LCL) FTR_VAL,
                          TO_DATE('{RPT_DT}', 'DD-MM-YY') AS RPT_DT,
                          CURRENT_TIMESTAMP ADD_TSTP
FROM
  (SELECT CUSTOMER_CDE,
          ACTUAL_BAL_LCL
   FROM DW_ANALYTICS.DW_DEPOSIT_FCT CS
   WHERE CATEGORY_CDE LIKE '10__'
     AND CUSTOMER_CDE IN
       (SELECT CUSTOMER_CDE
        FROM CINS_TMP_CUSTOMER_{RPT_DT_TBL})
     AND PROCESS_DT IN
       (SELECT MAX(PROCESS_DT)
        FROM DW_ANALYTICS.DW_DEPOSIT_FCT
        WHERE PROCESS_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')
          AND CATEGORY_CDE LIKE '10__' ) )
GROUP BY CUSTOMER_CDE