/*
Feature Name: CASA_HOLD
Derived From: DW_ACCOUNT_MASTER_DIM
*/
INSERT INTO {TBL_NM}
SELECT CUSTOMER_CDE,
       'CASA_HOLD' AS FTR_NM,
       '1' AS FTR_VAL,
       TO_DATE('{RPT_DT}', 'DD-MM-YY') AS RPT_DT,
       CURRENT_TIMESTAMP AS ADD_TSTP
FROM
  (SELECT DISTINCT CUSTOMER_CDE
   FROM DW_ANALYTICS.DW_ACCOUNT_MASTER_DIM
   WHERE ACTIVE = 1
     AND COMPANY_KEY = 1
     AND SUB_SECTOR_CDE IN ('1700',
                            '1602')
     AND CATEGORY_CDE LIKE '10__'
     AND TO_CHAR(CLOSE_DT) = '01-JAN-00'
     AND OPEN_DT <= TO_DATE('{RPT_DT}', 'DD-MM-YY') )