/*
Feature Name: EB_MBIB_CT_TXN_1M, EB_MBIB_CT_TXN_3M, EB_MBIB_CT_TXN_6M
Derived From: DW_EB_TRANSACTION_FCT, CINS_TMP_CUSTOMER_{RPT_DT_TBL}
*/
INSERT INTO {TBL_NM}
SELECT CUSTOMER_CDE,
       'EB_MBIB_CT_TXN_1M' FTR_NM,
                           COUNT(TXN_ID) FTR_VAL,
                           TO_DATE('{RPT_DT}', 'DD-MM-YY') AS RPT_DT,
                           CURRENT_TIMESTAMP ADD_TSTP
FROM DW_ANALYTICS.DW_EB_TRANSACTION_FCT
WHERE TXN_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')
  AND TXN_DT >= ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -1)
  AND TXN_STATUS = 'SUC'
  AND CUSTOMER_CDE IN
    (SELECT CUSTOMER_CDE
     FROM CINS_TMP_CUSTOMER_{RPT_DT_TBL})
GROUP BY CUSTOMER_CDE