/*
Feature Name: EB_SACOMPAY_SUM_TXN_AMT_1M, EB_SACOMPAY_SUM_TXN_AMT_3M, EB_SACOMPAY_SUM_TXN_AMT_6M
Derived From: DW_EWALL_TRANSACTION_FCT, CINS_TMP_CUSTOMER_{RPT_DT_TBL}
*/
INSERT INTO {TBL_NM}
SELECT CUSTOMER_CDE,
       'EB_SACOMPAY_SUM_TXN_AMT_1M' FTR_NM,
                                    NVL(SUM((TO_AMT)), 0) FTR_VAL,
                                    TO_DATE('{RPT_DT}', 'DD-MM-YY') AS RPT_DT,
                                    CURRENT_TIMESTAMP ADD_TSTP
FROM
  (SELECT DISTINCT TXN_ID,
                   CUSTOMER_CDE,
                   PROCESS_DT,
                   ABS(TO_AMT) TO_AMT
   FROM DW_ANALYTICS.DW_EWALL_TRANSACTION_FCT
   WHERE PROCESS_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')
     AND PROCESS_DT >= ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -1)
     AND TXN_STATUS = 'S'
     AND CUSTOMER_CDE IN
       (SELECT CUSTOMER_CDE
        FROM CINS_TMP_CUSTOMER_{RPT_DT_TBL}) ) TXN
GROUP BY CUSTOMER_CDE