/*
Feature Name: EB_SACOMPAY_CT_INACTIVE
Derived From: DW_EWALL_TRANSACTION_FCT, CINS_TMP_CUSTOMER_{RPT_DT_TBL}, DW_EWALL_USER_DIM
*/
INSERT INTO {TBL_NM}
SELECT CUSTOMER_CDE,
       'EB_SACOMPAY_CT_INACTIVE' FTR_NM,
                                 COUNT(*) FTR_VAL,
                                 TO_DATE('{RPT_DT}', 'DD-MM-YY') AS RPT_DT,
                                 CURRENT_TIMESTAMP ADD_TSTP
FROM
  (SELECT CUSTOMER_CDE,
          NVL(MONTHS_BETWEEN(LEAD(TXN_DT) OVER (PARTITION BY CUSTOMER_CDE
                                                ORDER BY TXN_DT), TXN_DT), MONTHS_BETWEEN(TO_DATE('{RPT_DT}', 'DD-MM-YY'), TXN_DT)) TXN_GAP
   FROM DW_ANALYTICS.DW_EWALL_TRANSACTION_FCT
   WHERE TXN_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')
     AND TXN_STATUS = 'S'
     AND CUSTOMER_CDE IN
       (SELECT CUSTOMER_CDE
        FROM CINS_TMP_CUSTOMER_{RPT_DT_TBL})
   UNION ALL SELECT B.CUSTOMER_CDE,
                    MONTHS_BETWEEN(MIN(TXN_DT), MAX(IDENTIFY_DT)) TXN_GAP
   FROM DW_ANALYTICS.DW_EWALL_TRANSACTION_FCT A
   JOIN DW_ANALYTICS.DW_EWALL_USER_DIM B ON A.CUSTOMER_CDE = B.CUSTOMER_CDE
   WHERE TXN_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')
     AND TXN_STATUS = 'S'
     AND TXN_DT > IDENTIFY_DT
     AND B.CUSTOMER_CDE IN
       (SELECT CUSTOMER_CDE
        FROM CINS_TMP_CUSTOMER_{RPT_DT_TBL})
   GROUP BY B.CUSTOMER_CDE)
WHERE TXN_GAP > 12
  AND TXN_GAP <= 36
GROUP BY CUSTOMER_CDE