CREATE OR REPLACE PROCEDURE CASA_PROC (RPT_DT IN DATE)

AS 

BEGIN

EXECUTE IMMEDIATE 'TRUNCATE TABLE CINS_FEATURE_STORE_CASA'; 

COMMIT; 

INSERT INTO CINS_FEATURE_STORE_CASA
SELECT
  DF.CUSTOMER_CDE,
  'CASA_BAL_AVG_1M' AS FTR_NM,
  AVG(DF.ACTUAL_BAL_LCL) AS FTR_VAL,
  TO_DATE(RPT_DT, 'DD-MM-YY') AS RPT_DT,
  CURRENT_TIMESTAMP AS ADD_TSTP
FROM DW_ANALYTICS.DW_DEPOSIT_FCT DF
JOIN CINS_TMP_CUSTOMER TMP ON DF.CUSTOMER_CDE = TMP.CUSTOMER_CDE
WHERE DF.CATEGORY_CDE LIKE '10__'
  AND ADD_MONTHS(TO_DATE(RPT_DT, 'DD-MM-YY'), -1) <= DF.PROCESS_DT
  AND DF.PROCESS_DT < TO_DATE(RPT_DT, 'DD-MM-YY')
GROUP BY DF.CUSTOMER_CDE;


COMMIT;


INSERT INTO CINS_FEATURE_STORE_CASA
SELECT
  DF.CUSTOMER_CDE,
  'CASA_BAL_MAX_1M' AS FTR_NM,
  MAX(DF.ACTUAL_BAL_LCL) AS FTR_VAL,
  TO_DATE(RPT_DT, 'DD-MM-YY') AS RPT_DT,
  CURRENT_TIMESTAMP AS ADD_TSTP
FROM DW_ANALYTICS.DW_DEPOSIT_FCT DF
JOIN CINS_TMP_CUSTOMER TMP ON DF.CUSTOMER_CDE = TMP.CUSTOMER_CDE
WHERE DF.CATEGORY_CDE LIKE '10__'
  AND ADD_MONTHS(TO_DATE(RPT_DT, 'DD-MM-YY'), -1) <= DF.PROCESS_DT
  AND DF.PROCESS_DT < TO_DATE(RPT_DT, 'DD-MM-YY')
GROUP BY DF.CUSTOMER_CDE;

COMMIT;

END;