CREATE OR REPLACE PROCEDURE CASA_PROC (RPT_DT IN DATE)

AS 

BEGIN

EXECUTE IMMEDIATE 'TRUNCATE TABLE CINS_FEATURE_STORE_CASA'; 

COMMIT; 

INSERT INTO CINS_FEATURE_STORE_CASA
SELECT
  DIM.CUSTOMER_CDE,
  'CASA_ACCT_ACTIVE_CT_12M' FTR_NM,
  COUNT(DISTINCT DIM.ACCT_ID) FTR_VAL,
  TO_DATE(RPT_DT, 'DD-MM-YY') AS RPT_DT,
  CURRENT_TIMESTAMP AS ADD_TSTP
FROM DW_ANALYTICS.DW_ACCOUNT_MASTER_DIM DIM
JOIN DW_ANALYTICS.DWA_STMT_EBANK FCT ON DIM.CUSTOMER_CDE = FCT.CUSTOMER_ID
JOIN DW_ANALYTICS.TRANSACTION_CODE TC ON FCT.TRANSACTION_CODE = TC.TRANSACTION_CODE
JOIN CINS_TMP_CUSTOMER TMP ON DIM.CUSTOMER_CDE = TMP.CUSTOMER_CDE
WHERE DIM.ACTIVE = 1
  AND DIM.ACCT_ID = FCT.ACCOUNT_NUMBER
  AND TC.INITIATION = 'CUSTOMER'
  AND FCT.PRODUCT_CATEGORY LIKE '10__'
  AND FCT.PROCESS_DT < TO_DATE(RPT_DT, 'DD-MM-YY')
  AND FCT.PROCESS_DT >= ADD_MONTHS(TO_DATE(RPT_DT, 'DD-MM-YY'), -12)
GROUP BY DIM.CUSTOMER_CDE;


COMMIT;


INSERT INTO CINS_FEATURE_STORE_CASA
SELECT
    TXN.CUSTOMER_ID AS CUSTOMER_CDE,
    'CASA_DAY_SINCE_LAST_TXN_CT_36M' AS FTR_NM,
    TO_DATE(RPT_DT, 'DD-MM-YY') - NVL(MAX(TXN.PROCESS_DT), ADD_MONTHS(TO_DATE(RPT_DT, 'DD-MM-YY'), -36)) AS FTR_VAL,
    TO_DATE(RPT_DT, 'DD-MM-YY') AS RPT_DT,
    CURRENT_TIMESTAMP AS ADD_TSTP
FROM DW_ANALYTICS.DWA_STMT_EBANK TXN
JOIN DW_ANALYTICS.TRANSACTION_CODE TC ON TXN.TRANSACTION_CODE = TC.TRANSACTION_CODE
JOIN CINS_TMP_CUSTOMER TMP ON TXN.CUSTOMER_ID = TMP.CUSTOMER_CDE
WHERE TXN.PRODUCT_CATEGORY LIKE '10__'
    AND TC.INITIATION = 'CUSTOMER'
    AND TXN.PROCESS_DT < TO_DATE(RPT_DT, 'DD-MM-YY')
    AND TXN.PROCESS_DT >= ADD_MONTHS(TO_DATE(RPT_DT, 'DD-MM-YY'), -36)
GROUP BY TXN.CUSTOMER_ID;


COMMIT;


INSERT INTO CINS_FEATURE_STORE_CASA
SELECT
    TXN.CUSTOMER_ID AS CUSTOMER_CDE,
    'CASA_TXN_CT_1M' AS FTR_NM,
    COUNT(DISTINCT TXN.STMT_ENTRY_ID) AS FTR_VAL,
    TO_DATE(RPT_DT, 'DD-MM-YY') AS RPT_DT,
    CURRENT_TIMESTAMP AS ADD_TSTP
FROM DW_ANALYTICS.DWA_STMT_EBANK TXN
JOIN DW_ANALYTICS.TRANSACTION_CODE TC ON TXN.TRANSACTION_CODE = TC.TRANSACTION_CODE
JOIN CINS_TMP_CUSTOMER TMP ON TXN.CUSTOMER_ID = TMP.CUSTOMER_CDE
WHERE TXN.PRODUCT_CATEGORY LIKE '10__'
    AND TC.INITIATION = 'CUSTOMER'
    AND TXN.PROCESS_DT < TO_DATE(RPT_DT, 'DD-MM-YY')
    AND TXN.PROCESS_DT >= ADD_MONTHS(TO_DATE(RPT_DT, 'DD-MM-YY'), -1)
GROUP BY TXN.CUSTOMER_ID;


COMMIT;


INSERT INTO CINS_FEATURE_STORE_CASA
SELECT
    TXN.CUSTOMER_ID AS CUSTOMER_CDE,
    'CASA_TXN_CT_3M' AS FTR_NM,
    COUNT(DISTINCT TXN.STMT_ENTRY_ID) AS FTR_VAL,
    TO_DATE(RPT_DT, 'DD-MM-YY') AS RPT_DT,
    CURRENT_TIMESTAMP AS ADD_TSTP
FROM DW_ANALYTICS.DWA_STMT_EBANK TXN
JOIN DW_ANALYTICS.TRANSACTION_CODE TC ON TXN.TRANSACTION_CODE = TC.TRANSACTION_CODE
JOIN CINS_TMP_CUSTOMER TMP ON TXN.CUSTOMER_ID = TMP.CUSTOMER_CDE
WHERE TXN.PRODUCT_CATEGORY LIKE '10__'
    AND TC.INITIATION = 'CUSTOMER'
    AND TXN.PROCESS_DT < TO_DATE(RPT_DT, 'DD-MM-YY')
    AND TXN.PROCESS_DT >= ADD_MONTHS(TO_DATE(RPT_DT, 'DD-MM-YY'), -3)
GROUP BY TXN.CUSTOMER_ID;


COMMIT;


INSERT INTO CINS_FEATURE_STORE_CASA
SELECT
    TXN.CUSTOMER_ID AS CUSTOMER_CDE,
    'CASA_TXN_CT_6M' AS FTR_NM,
    COUNT(DISTINCT TXN.STMT_ENTRY_ID) AS FTR_VAL,
    TO_DATE(RPT_DT, 'DD-MM-YY') AS RPT_DT,
    CURRENT_TIMESTAMP AS ADD_TSTP
FROM DW_ANALYTICS.DWA_STMT_EBANK TXN
JOIN DW_ANALYTICS.TRANSACTION_CODE TC ON TXN.TRANSACTION_CODE = TC.TRANSACTION_CODE
JOIN CINS_TMP_CUSTOMER TMP ON TXN.CUSTOMER_ID = TMP.CUSTOMER_CDE
WHERE TXN.PRODUCT_CATEGORY LIKE '10__'
    AND TC.INITIATION = 'CUSTOMER'
    AND TXN.PROCESS_DT < TO_DATE(RPT_DT, 'DD-MM-YY')
    AND TXN.PROCESS_DT >= ADD_MONTHS(TO_DATE(RPT_DT, 'DD-MM-YY'), -6)
GROUP BY TXN.CUSTOMER_ID;


COMMIT;


INSERT INTO CINS_FEATURE_STORE_CASA
SELECT
    TXN.CUSTOMER_ID AS CUSTOMER_CDE,
    'CASA_TXN_CT_12M' AS FTR_NM,
    COUNT(DISTINCT TXN.STMT_ENTRY_ID) AS FTR_VAL,
    TO_DATE(RPT_DT, 'DD-MM-YY') AS RPT_DT,
    CURRENT_TIMESTAMP AS ADD_TSTP
FROM DW_ANALYTICS.DWA_STMT_EBANK TXN
JOIN DW_ANALYTICS.TRANSACTION_CODE TC ON TXN.TRANSACTION_CODE = TC.TRANSACTION_CODE
JOIN CINS_TMP_CUSTOMER TMP ON TXN.CUSTOMER_ID = TMP.CUSTOMER_CDE
WHERE TXN.PRODUCT_CATEGORY LIKE '10__'
    AND TC.INITIATION = 'CUSTOMER'
    AND TXN.PROCESS_DT < TO_DATE(RPT_DT, 'DD-MM-YY')
    AND TXN.PROCESS_DT >= ADD_MONTHS(TO_DATE(RPT_DT, 'DD-MM-YY'), -12)
GROUP BY TXN.CUSTOMER_ID;


COMMIT;


INSERT INTO CINS_FEATURE_STORE_CASA
SELECT
    CS.CUSTOMER_CDE,
    'CASA_BAL_SUM_NOW' AS FTR_NM,
    SUM(CS.ACTUAL_BAL_LCL) AS FTR_VAL,
    TO_DATE(RPT_DT, 'DD-MM-YY') AS RPT_DT,
    CURRENT_TIMESTAMP AS ADD_TSTP
FROM DW_ANALYTICS.DW_DEPOSIT_FCT CS
JOIN CINS_TMP_CUSTOMER TMP ON CS.CUSTOMER_CDE = TMP.CUSTOMER_CDE
WHERE CS.CATEGORY_CDE LIKE '10__'
    AND CS.PROCESS_DT = (
        SELECT MAX(PROCESS_DT)
        FROM DW_ANALYTICS.DW_DEPOSIT_FCT
        WHERE PROCESS_DT < TO_DATE(RPT_DT, 'DD-MM-YY')
          AND CATEGORY_CDE LIKE '10__'
    )
GROUP BY CS.CUSTOMER_CDE;


COMMIT;


INSERT INTO CINS_FEATURE_STORE_CASA
SELECT
  DF.CUSTOMER_CDE,
  'CASA_BAL_AVG_1M' AS FTR_NM,
  AVG(DF.ACTUAL_BAL_LCL) AS FTR_VAL,
  TO_DATE(RPT_DT, 'DD-MM-YY') AS RPT_DT,
  CURRENT_TIMESTAMP AS ADD_TSTP
FROM DW_ANALYTICS.DW_DEPOSIT_FCT DF
JOIN CINS_TMP_CUSTOMER TMP ON DF.CUSTOMER_CDE = TMP.CUSTOMER_CDE
WHERE DF.CATEGORY_CDE LIKE '10__'
  AND ADD_MONTHS(TO_DATE(RPT_DT, 'DD-MM-YY'), -1) <= DF.PROCESS_DT
  AND DF.PROCESS_DT < TO_DATE(RPT_DT, 'DD-MM-YY')
GROUP BY DF.CUSTOMER_CDE;


COMMIT;


INSERT INTO CINS_FEATURE_STORE_CASA
SELECT
  DF.CUSTOMER_CDE,
  'CASA_BAL_MAX_1M' AS FTR_NM,
  MAX(DF.ACTUAL_BAL_LCL) AS FTR_VAL,
  TO_DATE(RPT_DT, 'DD-MM-YY') AS RPT_DT,
  CURRENT_TIMESTAMP AS ADD_TSTP
FROM DW_ANALYTICS.DW_DEPOSIT_FCT DF
JOIN CINS_TMP_CUSTOMER TMP ON DF.CUSTOMER_CDE = TMP.CUSTOMER_CDE
WHERE DF.CATEGORY_CDE LIKE '10__'
  AND ADD_MONTHS(TO_DATE(RPT_DT, 'DD-MM-YY'), -1) <= DF.PROCESS_DT
  AND DF.PROCESS_DT < TO_DATE(RPT_DT, 'DD-MM-YY')
GROUP BY DF.CUSTOMER_CDE;


COMMIT;


INSERT INTO CINS_FEATURE_STORE_CASA
SELECT
  DF.CUSTOMER_CDE,
  'CASA_BAL_MIN_1M' AS FTR_NM,
  MIN(DF.ACTUAL_BAL_LCL) AS FTR_VAL,
  TO_DATE(RPT_DT, 'DD-MM-YY') AS RPT_DT,
  CURRENT_TIMESTAMP AS ADD_TSTP
FROM DW_ANALYTICS.DW_DEPOSIT_FCT DF
JOIN CINS_TMP_CUSTOMER TMP ON DF.CUSTOMER_CDE = TMP.CUSTOMER_CDE
WHERE DF.CATEGORY_CDE LIKE '10__'
  AND ADD_MONTHS(TO_DATE(RPT_DT, 'DD-MM-YY'), -1) <= DF.PROCESS_DT
  AND DF.PROCESS_DT < TO_DATE(RPT_DT, 'DD-MM-YY')
GROUP BY DF.CUSTOMER_CDE;


COMMIT;


INSERT INTO CINS_FEATURE_STORE_CASA
SELECT
    TXN.CUSTOMER_ID AS CUSTOMER_CDE,
    'CASA_TXN_AMT_SUM_1M' AS FTR_NM,
    NVL(SUM(ABS(TXN.AMT_LCY)), 0) AS FTR_VAL,
    TO_DATE(RPT_DT, 'DD-MM-YY') AS RPT_DT,
    CURRENT_TIMESTAMP AS ADD_TSTP
FROM DW_ANALYTICS.DWA_STMT_EBANK TXN
JOIN DW_ANALYTICS.TRANSACTION_CODE TC ON TXN.TRANSACTION_CODE = TC.TRANSACTION_CODE
JOIN CINS_TMP_CUSTOMER TMP ON TXN.CUSTOMER_ID = TMP.CUSTOMER_CDE
WHERE TXN.PRODUCT_CATEGORY LIKE '10__'
    AND TC.INITIATION = 'CUSTOMER' 
    AND TXN.PROCESS_DT < TO_DATE(RPT_DT, 'DD-MM-YY')
    AND TXN.PROCESS_DT >= ADD_MONTHS(TO_DATE(RPT_DT, 'DD-MM-YY'), -1)
GROUP BY TXN.CUSTOMER_ID;


COMMIT;


INSERT INTO CINS_FEATURE_STORE_CASA
SELECT
    TXN.CUSTOMER_ID AS CUSTOMER_CDE,
    'CASA_TXN_AMT_SUM_3M' AS FTR_NM,
    NVL(SUM(ABS(TXN.AMT_LCY)), 0) AS FTR_VAL,
    TO_DATE(RPT_DT, 'DD-MM-YY') AS RPT_DT,
    CURRENT_TIMESTAMP AS ADD_TSTP
FROM DW_ANALYTICS.DWA_STMT_EBANK TXN
JOIN DW_ANALYTICS.TRANSACTION_CODE TC ON TXN.TRANSACTION_CODE = TC.TRANSACTION_CODE
JOIN CINS_TMP_CUSTOMER TMP ON TXN.CUSTOMER_ID = TMP.CUSTOMER_CDE
WHERE TXN.PRODUCT_CATEGORY LIKE '10__'
    AND TC.INITIATION = 'CUSTOMER' 
    AND TXN.PROCESS_DT < TO_DATE(RPT_DT, 'DD-MM-YY')
    AND TXN.PROCESS_DT >= ADD_MONTHS(TO_DATE(RPT_DT, 'DD-MM-YY'), -3)
GROUP BY TXN.CUSTOMER_ID;


COMMIT;


INSERT INTO CINS_FEATURE_STORE_CASA
SELECT
    TXN.CUSTOMER_ID AS CUSTOMER_CDE,
    'CASA_TXN_AMT_SUM_6M' AS FTR_NM,
    NVL(SUM(ABS(TXN.AMT_LCY)), 0) AS FTR_VAL,
    TO_DATE(RPT_DT, 'DD-MM-YY') AS RPT_DT,
    CURRENT_TIMESTAMP AS ADD_TSTP
FROM DW_ANALYTICS.DWA_STMT_EBANK TXN
JOIN DW_ANALYTICS.TRANSACTION_CODE TC ON TXN.TRANSACTION_CODE = TC.TRANSACTION_CODE
JOIN CINS_TMP_CUSTOMER TMP ON TXN.CUSTOMER_ID = TMP.CUSTOMER_CDE
WHERE TXN.PRODUCT_CATEGORY LIKE '10__'
    AND TC.INITIATION = 'CUSTOMER' 
    AND TXN.PROCESS_DT < TO_DATE(RPT_DT, 'DD-MM-YY')
    AND TXN.PROCESS_DT >= ADD_MONTHS(TO_DATE(RPT_DT, 'DD-MM-YY'), -6)
GROUP BY TXN.CUSTOMER_ID;


COMMIT;


INSERT INTO CINS_FEATURE_STORE_CASA
SELECT
    TXN.CUSTOMER_ID AS CUSTOMER_CDE,
    'CASA_TXN_AMT_SUM_12M' AS FTR_NM,
    NVL(SUM(ABS(TXN.AMT_LCY)), 0) AS FTR_VAL,
    TO_DATE(RPT_DT, 'DD-MM-YY') AS RPT_DT,
    CURRENT_TIMESTAMP AS ADD_TSTP
FROM DW_ANALYTICS.DWA_STMT_EBANK TXN
JOIN DW_ANALYTICS.TRANSACTION_CODE TC ON TXN.TRANSACTION_CODE = TC.TRANSACTION_CODE
JOIN CINS_TMP_CUSTOMER TMP ON TXN.CUSTOMER_ID = TMP.CUSTOMER_CDE
WHERE TXN.PRODUCT_CATEGORY LIKE '10__'
    AND TC.INITIATION = 'CUSTOMER' 
    AND TXN.PROCESS_DT < TO_DATE(RPT_DT, 'DD-MM-YY')
    AND TXN.PROCESS_DT >= ADD_MONTHS(TO_DATE(RPT_DT, 'DD-MM-YY'), -12)
GROUP BY TXN.CUSTOMER_ID;

COMMIT;

END;