WITH 
T0 AS (
    SELECT * FROM DW_ANALYTICS.DW_CUST_PRODUCT_LOC_FCT
    WHERE SD_TKTT = 1
),
T1 AS (
    SELECT CUSTOMER_CDE, PROCESS_DT,
        MAX(CASE
            WHEN CUST_STATUS = 'HOAT DONG' THEN 2
            WHEN CUST_STATUS = 'NGU DONG' THEN 1
            WHEN CUST_STATUS = 'DONG BANG' THEN 0
        END) AS CUST_STT 
    FROM T0
    WHERE PROCESS_DT = TO_DATE('31-12-2022', 'DD-MM-YY')
    OR PROCESS_DT = TO_DATE('31-01-2023', 'DD-MM-YY')
    OR PROCESS_DT = TO_DATE('28-02-2023', 'DD-MM-YY')
    OR PROCESS_DT = TO_DATE('31-03-2023', 'DD-MM-YY')
    OR PROCESS_DT = TO_DATE('30-04-2023', 'DD-MM-YY')
    OR PROCESS_DT = TO_DATE('31-05-2023', 'DD-MM-YY')
    OR PROCESS_DT = TO_DATE('30-06-2023', 'DD-MM-YY')
    OR PROCESS_DT = TO_DATE('31-07-2023', 'DD-MM-YY')
    OR PROCESS_DT = TO_DATE('31-08-2023', 'DD-MM-YY')
    OR PROCESS_DT = TO_DATE('30-09-2023', 'DD-MM-YY')
    OR PROCESS_DT = TO_DATE('31-10-2023', 'DD-MM-YY')
    OR PROCESS_DT = TO_DATE('30-11-2023', 'DD-MM-YY')
    OR PROCESS_DT = TO_DATE('31-12-2023', 'DD-MM-YY')
    GROUP BY CUSTOMER_CDE, PROCESS_DT
),
T2 AS (
    SELECT PROCESS_DT, CUST_STT, COUNT(DISTINCT CUSTOMER_CDE) AS NUM_CUST
    FROM T1
    GROUP BY PROCESS_DT, CUST_STT
    ORDER BY 1, 2
)
SELECT * FROM T2;