# Format always DD-MM-YY
REPORT_DATE:
    REQUEST:
        TYPE: 'S' # S is SELECT-DAYS, R is RANGE from Start to End (auto get min and include max date) 
        # DATES: ['01-07-2023', '01-08-2023', '01-09-2023', '01-10-2023', '01-11-2023']
        # DATES: ['11-06-2023', '01-07-2023', '01-11-2023']
        DATES: ['11-06-2023']
FEATURE_STORE_TBL: 'CINS_FEATURE_STORE_V2'
