-- Create

CREATE TABLE CINS_TMP_ALY_CUST_SAMPLE4 AS (
    SELECT CUSTOMER_CDE FROM (
        SELECT DISTINCT CUSTOMER_CDE 
        FROM DW_ANALYTICS.DW_CUSTOMER_FULL_DIM
        ORDER BY DBMS_RANDOM.VALUE)
    WHERE ROWNUM <= 5000000
);

-- Test
SELECT COUNT(DISTINCT CUSTOMER_CDE) FROM CINS_TMP_ALY_CUST_SAMPLE4;

-- Drop
DROP TABLE CINS_TMP_ALY_CUST_SAMPLE4;
