/*
Feature Name: CASA_CT_ACCT_ACTIVE
Derived From: 
  DW_ANALYTICS.DW_ACCOUNT_MASTER_DIM:  
    - ACCT_ID
    - ACTIVE
    - CUSTOMER_CDE
  DW_ANALYTICS.DWA_STMT_EBANK: 
    - TRANSACTION_CODE
    - CUSTOMER_ID
    - PRODUCT_CATEGORY
    - ACCOUNT_NUMBER
    - PROCESS_DT
  DW_ANALYTICS.TRANSACTION_CODE: 
    - TRANSACTION_CODE
    - INITIATION
  CINS_TMP_CUSTOMER_{RPT_DT_TBL}:
    - CUSTOMER_CDE
Tags: 
  - CASA
TW: 12M
*/
INSERT INTO {TBL_NM}
SELECT
  DIM.CUSTOMER_CDE,
  'CASA_CT_ACCT_ACTIVE' FTR_NM,
  COUNT(DISTINCT DIM.ACCT_ID) FTR_VAL,
  TO_DATE('{RPT_DT}', 'DD-MM-YY') AS RPT_DT,
  CURRENT_TIMESTAMP AS ADD_TSTP
FROM DW_ANALYTICS.DW_ACCOUNT_MASTER_DIM DIM
JOIN DW_ANALYTICS.DWA_STMT_EBANK FCT ON DIM.CUSTOMER_CDE = FCT.CUSTOMER_ID
JOIN DW_ANALYTICS.TRANSACTION_CODE TC ON FCT.TRANSACTION_CODE = TC.TRANSACTION_CODE
JOIN CINS_TMP_CUSTOMER_{RPT_DT_TBL} TMP ON DIM.CUSTOMER_CDE = TMP.CUSTOMER_CDE
WHERE DIM.ACTIVE = 1
  AND FCT.PRODUCT_CATEGORY LIKE '10__'
  AND FCT.PROCESS_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')
  AND FCT.PROCESS_DT >= ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -12)
GROUP BY DIM.CUSTOMER_CDE;