/*
Feature Name: CASA_HOLD
Derived From: 
    DW_ACCOUNT_MASTER_DIM:
        - CUSTOMER_CDE
        - ACTIVE
        - COMPANY_KEY
        - SUB_SECTOR_CDE
        - CATEGORY_CDE
        - OPEN_DT
        - CLOSE_DT
Tags:
    - CASA
TW: 1M
*/
INSERT INTO {TBL_NM}
SELECT
    DISTINCT AMD.CUSTOMER_CDE,
    'CASA_HOLD' AS FTR_NM,
    '1' AS FTR_VAL,
    TO_DATE('{RPT_DT}', 'DD-MM-YY') AS RPT_DT,
    CURRENT_TIMESTAMP AS ADD_TSTP
FROM DW_ANALYTICS.DW_ACCOUNT_MASTER_DIM AMD
WHERE AMD.ACTIVE = 1
    AND AMD.COMPANY_KEY = 1
    AND AMD.SUB_SECTOR_CDE IN ('1700', '1602')
    AND AMD.CATEGORY_CDE LIKE '10__'
    AND TO_CHAR(AMD.CLOSE_DT) = '01-JAN-00'
    AND AMD.OPEN_DT <= TO_DATE('{RPT_DT}', 'DD-MM-YY');
