/*
Feature Name: EB_CT_TXN_3M
Derived From: DW_EB_TRANSACTION_FCT, CINS_TMP_CUSTOMER_{RPT_DT_TBL}
*/
INSERT INTO {TBL_NM}
SELECT CUSTOMER_CDE,
       'EB_CT_TXN_3M' FTR_NM,
                      count(DISTINCT txn_id) FTR_VAL,
                      TO_DATE('{RPT_DT}', 'DD-MM-YY') AS RPT_DT,
                      CURRENT_TIMESTAMP ADD_TSTP
FROM
  (SELECT CUSTOMER_CDE,
          txn_id,
          txn_dt
   FROM DW_ANALYTICS.DW_EB_TRANSACTION_FCT
   WHERE CUSTOMER_CDE IN
       (SELECT CUSTOMER_CDE
        FROM CINS_TMP_CUSTOMER_{RPT_DT_TBL})
     AND TXN_ENTRY_STATUS = 'SUC' )
WHERE TXN_DT < TO_DATE('{RPT_DT}', 'DD-MM-YY')
  AND TXN_DT >= ADD_MONTHS(TO_DATE('{RPT_DT}', 'DD-MM-YY'), -3)
GROUP BY CUSTOMER_CDE